let catalogEstel = [
  {
    id: "el1",
    name: "СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 250 МЛ",
    img: "https://i.ibb.co/h98SL8W/ESTEL-PRIMA-BLONDE.jpg",
    quantity: 1,
    price: 495,
    productType: "shampoo",
  },
  {
    id: "el2",
    name: "СЕРЕБРИСТЫЙ ШАМПУНЬ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ",
    img: "https://i.ibb.co/D4n9Kyk/ESTEL-PRIMA-BLONDE-1000.jpg",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el3",
    name: "СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 200 МЛ",
    img: "https://i.ibb.co/JnWDZWR/ESTEL-PRIMA-BLONDE.jpg",
    price: 495,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el4",
    name: "СЕРЕБРИСТАЯ МАСКА ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 300 МЛ",
    img: "https://i.ibb.co/jHX2vZt/ESTEL-PRIMA-BLONDE.jpg",
    price: 710,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el5",
    name: "БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE, 200 МЛ",
    img: "https://i.ibb.co/MR1LJvH/ESTEL-PRIMA-BLONDE.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el6",
    name: "БЛЕСК-ШАМПУНЬ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE, 1000 МЛ",
    img: "https://i.ibb.co/wSSy8j7/ESTEL-PRIMA-BLONDE-1000.jpg",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el7",
    name: "БЛЕСК-БАЛЬЗАМ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE, 200 МЛ",
    img: "https://i.ibb.co/k1YMh47/ESTEL-PRIMA-BLONDE.jpg",
    price: 495,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el8",
    name: "КОМФОРТ-МАСКА ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE, 300 МЛ",
    img: "https://i.ibb.co/vjhWNWy/ESTEL-PRIMA-BLONDE.jpg",
    price: 710,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el9",
    name: "ДВУХФАЗНЫЙ СПРЕЙ ДЛЯ СВЕТЛЫХ ВОЛОС ESTEL PRIMA BLONDE",
    img: "https://i.ibb.co/BnZQ4Ck/ESTEL-PRIMA-BLONDE.jpg",
    price: 475,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el10",
    name: "СЕРЕБРИСТЫЙ БАЛЬЗАМ ДЛЯ ХОЛОДНЫХ ОТТЕНКОВ БЛОНД ESTEL PRIMA BLONDE, 1000 МЛ",
    img: "https://i.ibb.co/NWjVHNJ/ESTEL-PRIMA-BLONDE-1000.jpg",
    price: 1200,
    quantity: 1,
    productType: "balsam",
  },
  //ТОНИРУЮЩИЕ МАСКИ NEWTONE HAUTE COUTURE, 60 МЛ
  {
    id: "el11",
    name: "NEWTONE 10-6, СВЕТЛЫЙ БЛОНДИН ФИОЛЕТОВЫЙ, 60 МЛ",
    img: "https://i.ibb.co/VSP8PNT/NEWTONE-10-6-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el12",
    name: "NEWTONE 10-7, СВЕТЛЫЙ БЛОНДИН КОРИЧНЕВЫЙ, 60 МЛ",
    img: "https://i.ibb.co/WVdxwHm/NEWTONE-10-7-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el13",
    name: "NEWTONE 10-76, СВЕТЛЫЙ БЛОНДИН КОРИЧНЕВО-ФИОЛЕТОВЫЙ, 60 МЛ.webp",
    img: "https://i.ibb.co/hDMDL1x/NEWTONE-10-76-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el14",
    name: "NEWTONE 7-34, РУСЫЙ ЗОЛОТИСТО-МЕДНЫЙ, 60 МЛ",
    img: "https://i.ibb.co/d5Wy23d/NEWTONE-7-34-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el15",
    name: "NEWTONE 7-44, РУСЫЙ МЕДНЫЙ ИНТЕНСИВНЫЙ, 60 МЛ.webp",
    img: "https://i.ibb.co/Lt1Z1Yt/NEWTONE-7-44-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el16",
    name: "NEWTONE 7-56, РУСЫЙ КРАСНО-ФИОЛЕТОВЫЙ, 60 МЛ",
    img: "https://i.ibb.co/Qk1H5yD/NEWTONE-7-56-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el17",
    name: "NEWTONE 7-75, РУСЫЙ КОРИЧНЕВО-КРАСНЫЙ, 60 МЛ",
    img: "https://i.ibb.co/qmgvKVk/NEWTONE-7-75-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el18",
    name: "NEWTONE 8-36, СВЕТЛО-РУСЫЙ ЗОЛОТИСТО-ФИОЛЕТОВЫЙ, 60 МЛ",
    img: "https://i.ibb.co/bQ8fWmy/NEWTONE-8-36-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el19",
    name: "NEWTONE 8-61, СВЕТЛО-РУСЫЙ ФИОЛЕТОВО-ПЕПЕЛЬНЫЙ, 60 МЛ",
    img: "https://i.ibb.co/drSpGfV/NEWTONE-8-61-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el20",
    name: "NEWTONE 8-76, СВЕТЛО-РУСЫЙ КОРИЧНЕВО-ФИОЛЕТОВЫЙ, 60 МЛ",
    img: "https://i.ibb.co/LRgztr9/NEWTONE-8-76-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el21",
    name: "NEWTONE 9-65, БЛОНДИН ФИОЛЕТОВО-КРАСНЫЙ, 60 МЛ",
    img: "https://i.ibb.co/wZq908K/NEWTONE-9-65-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el22",
    name: "NEWTONE 10-73, СВЕТЛЫЙ БЛОНДИН КОРИЧНЕВО-ЗОЛОТИСТЫЙ, 60 МЛ",
    img: "https://i.ibb.co/RSxjHf9/NEWTONE-10-73-60.jpg",
    price: 170,
    quantity: 1,
    productType: "mask",
  },
  //СЕРИЯ OTIUM AQUA (ОТИУМ АКВА) ДЛЯ ИНТЕНСИВНОГО УВЛАЖНЕНИЯ ВОЛОС - #1
  {
    id: "el23",
    name: "НАБОР OTIUM AQUA",
    img: "https://i.ibb.co/x3xdt6J/OTIUM-AQUA.png",
    price: 790,
    quantity: 1,
    productType: "set",
  },
  {
    id: "el24",
    name: "ШАМПУНЬ ДЛЯ ИНТЕНСИВНОГО УВЛАЖНЕНИЯ ВОЛОС OTIUM AQUA, 250 МЛ",
    img: "https://i.ibb.co/99Hk0j8/OTIUM-AQUA.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el25",
    name: "ШАМПУНЬ ДЛЯ ИНТЕНСИВНОГО УВЛАЖНЕНИЯ ВОЛОС OTIUM AQUA, 1000 МЛ",
    img: "https://i.ibb.co/Sf1DxCj/OTIUM-AQUA-1000.jpg",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el26",
    name: "БАЛЬЗАМ ДЛЯ ИНТЕНСИВНОГО УВЛАЖНЕНИЯ ВОЛОС OTIUM AQUA, 250 МЛ",
    img: "https://i.ibb.co/99Hk0j8/OTIUM-AQUA.jpg",
    price: 495,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el27",
    name: "БАЛЬЗАМ ДЛЯ ИНТЕНСИВНОГО УВЛАЖНЕНИЯ ВОЛОС OTIUM AQUA, 1000 МЛ",
    img: "https://i.ibb.co/6HyTF9w/OTIUM-AQUA-1000.jpg",
    price: 1200,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el28",
    name: "СПРЕЙ ДЛЯ ИНТЕНСИВНОГО УВЛАЖНЕНИЯ ВОЛОС OTIUM AQUA, 200 МЛ",
    img: "https://i.ibb.co/ns3Bvrt/OTIUM-AQUA.jpg",
    price: 495,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el29",
    name: 'СЫВОРОТКА ДЛЯ ВОЛОС "ЭКСПРЕСС-УВЛАЖНЕНИЕ" OTIUM AQUA, 100 МЛ',
    img: "https://i.ibb.co/Qnxb9HX/OTIUM-AQUA.jpg",
    price: 495,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el30",
    name: "КОМФОРТ-МАСКА ДЛЯ ИНТЕНСИВНОГО УВЛАЖНЕНИЯ ВОЛОС OTIUM AQUA, 300 МЛ",
    img: "https://i.ibb.co/tmPVSvB/OTIUM-AQUA.jpg",
    price: 710,
    quantity: 1,
    productType: "mask",
  },
  //СЕРИЯ OTIUM COLOR LIFE (ОТИУМ КОЛОР ЛАЙФ) ДЛЯ ОКРАШЕННЫХ ВОЛОС - #2
  {
    id: "el31",
    name: "НАБОР OTIUM COLOR LIFE",
    img: "https://i.ibb.co/tYvwqgN/OTIUM-COLOR-LIFE.png",
    price: 790,
    quantity: 1,
    productType: "set",
  },
  {
    id: "el32",
    name: "ДЕЛИКАТНЫЙ ШАМПУНЬ ДЛЯ ОКРАШЕННЫХ ВОЛОС OTIUM COLOR LIFE, 250 МЛ",
    img: "https://i.ibb.co/HYNNmsx/OTIUM-COLOR-LIFE.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el33",
    name: "ДЕЛИКАТНЫЙ ШАМПУНЬ ДЛЯ ОКРАШЕННЫХ ВОЛОС OTIUM COLOR LIFE, 1000 МЛ",
    img: "https://i.ibb.co/D1BpjhH/OTIUM-COLOR-LIFE-1000.jpg",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el34",
    name: "БАЛЬЗАМ-СИЯНИЕ ДЛЯ ОКРАШЕННЫХ ВОЛОС OTIUM COLOR LIFE, 200 МЛ",
    img: "https://i.ibb.co/cbmczVV/OTIUM-COLOR-LIFE.jpg",
    price: 495,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el35",
    name: "БАЛЬЗАМ-СИЯНИЕ ДЛЯ ОКРАШЕННЫХ ВОЛОС OTIUM COLOR LIFE, 1000 МЛ",
    img: "https://i.ibb.co/6ysC2zj/OTIUM-COLOR-LIFE-1000.jpg",
    price: 1200,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el36",
    name: 'СПРЕЙ-УХОД ДЛЯ ВОЛОС "ЯРКОСТЬ ЦВЕТА" OTIUM COLOR LIFE, 100 МЛ',
    img: "https://i.ibb.co/94mGN8J/OTIUM-COLOR-LIFE.jpg",
    price: 495,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el37",
    name: "МАСКА-КОКТЕЙЛЬ ДЛЯ ОКРАШЕННЫХ ВОЛОС OTIUM COLOR LIFEБ 100 МЛ",
    img: "https://i.ibb.co/wKYfT1y/OTIUM-COLOR-LIFE.jpg",
    price: 495,
    quantity: 1,
    productType: "mask",
  },
  //СЕРИЯ OTIUM DIAMOND (ОТИУМ ДАЙМОНД) ДЛЯ ГЛАДКОСТИ И БЛЕСКА ВОЛОС - #3
  {
    id: "el38",
    name: "НАБОР OTIUM DIAMOND",
    img: "https://i.ibb.co/rcfPjFH/OTIUM-DIAMOND.png",
    price: 790,
    quantity: 1,
    productType: "set",
  },
  {
    id: "el39",
    name: "БЛЕСК-ШАМПУНЬ ДЛЯ ГЛАДКОСТИ И БЛЕСКА ВОЛОС OTIUM DIAMOND, 250 МЛ",
    img: "https://i.ibb.co/tqzFHLK/OTIUM-DIAMOND.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el40",
    name: "БЛЕСК-БАЛЬЗАМ ДЛЯ ГЛАДКОСТИ И БЛЕСКА ВОЛОС OTIUM DIAMOND, 1000 МЛ",
    img: "https://i.ibb.co/5xYdYVh/OTIUM-DIAMOND.jpg",
    price: 1000,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el41",
    name: "ТЕРМОЗАЩИТА ДЛЯ ВОЛОС OTIUM DIAMOND, 100 МЛ",
    img: "https://i.ibb.co/6wvnLD0/OTIUM-DIAMOND.jpg",
    price: 475,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el42",
    name: "ДРАГОЦЕННОЕ МАСЛО ДЛЯ ГЛАДКОСТИ И БЛЕСКА ВОЛОС OTIUM DIAMOND, 100 МЛ",
    img: "https://i.ibb.co/BG2GXmh/OTIUM-DIAMOND.jpg",
    price: 810,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el43",
    name: "ШЁЛКОВАЯ МАСКА ДЛЯ ГЛАДКОСТИ И БЛЕСКА ВОЛОС OTIUM DIAMOND, 300 МЛ",
    img: "https://i.ibb.co/FHxJ843/OTIUM-DIAMOND.jpg",
    price: 710,
    quantity: 1,
    productType: "mask",
  },
  //СЕРИЯ OTIUM MIRACLE REVIVE (ОТИУМ МИРАКЛ РЕВАЙВ) ДЛЯ ВОССТАНОВЛЕНИЯ ВОЛОС - #4
  {
    id: "el44",
    name: "НАБОР OTIUM MIRACLE REVIVE",
    img: "https://i.ibb.co/5By69YD/OTIUM-MIRACLE-REVIVE.png",
    price: 790,
    quantity: 1,
    productType: "set",
  },
  {
    id: "el45",
    name: "ШАМПУНЬ-УХОД ДЛЯ ВОССТАНОВЛЕНИЯ ВОЛОС OTIUM MIRACLE REVIVE, 250 МЛ",
    img: "https://i.ibb.co/Bg1Y2D2/OTIUM-MIRACLE-REVIVE.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el46",
    name: "ШАМПУНЬ-УХОД ДЛЯ ВОССТАНОВЛЕНИЯ ВОЛОС OTIUM MIRACLE REVIVE, 1000 МЛ",
    img: "https://i.ibb.co/Bg1Y2D2/OTIUM-MIRACLE-REVIVE.jpg",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el47",
    name: "БАЛЬЗАМ-ПИТАНИЕ ДЛЯ ВОССТАНОВЛЕНИЯ ВОЛОС OTIUM MIRACLE REVIVE, 200 МЛ",
    img: "https://i.ibb.co/B2CLsjg/OTIUM-MIRACLE-REVIVE.jpg",
    price: 495,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el48",
    name: "БАЛЬЗАМ-ПИТАНИЕ ДЛЯ ВОССТАНОВЛЕНИЯ ВОЛОС OTIUM MIRACLE REVIVE, 1000 МЛ",
    img: "https://i.ibb.co/B2CLsjg/OTIUM-MIRACLE-REVIVE.jpg",
    price: 1200,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el49",
    name: 'ЭЛИКСИР ДЛЯ ВОЛОС "СИЛА КЕРАТИНА" OTIUM MIRACLE REVIVE, 100 МЛ',
    img: "https://i.ibb.co/6FVZjmt/OTIUM-MIRACLE-REVIVE.jpg",
    price: 475,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el50",
    name: "ИНТЕНСИВНАЯ МАСКА ДЛЯ ВОССТАНОВЛЕНИЯ ВОЛОС OTIUM MIRACLE REVIVE, 300 МЛ",
    img: "https://i.ibb.co/FHYkgRK/OTIUM-MIRACLE-REVIVE.jpg",
    price: 710,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el51",
    name: 'СЫВОРОТКА "РЕКОНСТРУКЦИЯ КОНЧИКОВ ВОЛОС" OTIUM MIRACLE REVIVE, 100 МЛ',
    img: "https://i.ibb.co/yyfffPS/OTIUM-MIRACLE-REVIVE.jpg",
    price: 695,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el52",
    name: 'СЫВОРОТКА-ВУАЛЬ ДЛЯ ВОЛОС "МГНОВЕННОЕ ВОССТАНОВЛЕНИЕ" OTIUM MIRACLE REVIVE, 5*23 МЛ',
    img: "https://i.ibb.co/sbfY5Hq/OTIUM-MIRACLE-REVIVE.jpg",
    price: 695,
    quantity: 1,
    productType: "care",
  },
  //СЕРИЯ OTIUM UNIQUE (ОТИУМ УНИК) СПЕЦИАЛЬНЫЙ УХОД ЗА КОЖЕЙ ГОЛОВЫ - #5
  {
    id: "el53",
    name: "ШАМПУНЬ-АКТИВАТОР РОСТА ВОЛОС OTIUM UNIQUE. 250 МЛ",
    img: "https://i.ibb.co/SQZvNms/OTIUM-UNIQUE.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el54",
    name: "ШАМПУНЬ ОТ ПЕРХОТИ OTIUM UNIQUE, 250 МЛ",
    img: "https://i.ibb.co/QcBPscb/OTIUM-UNIQUE.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el55",
    name: "ШАМПУНЬ ДЛЯ ЖИРНОЙ КОЖИ ГОЛОВЫ И СУХИХ ВОЛОС OTIUM UNIQUE, 250 МЛ",
    img: "https://i.ibb.co/b290pBL/OTIUM-UNIQUE.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el56",
    name: "ТОНИК-АКТИВАТОР РОСТА ВОЛОС OTIUM UNIQUE, 100 МЛ",
    img: "https://i.ibb.co/Mk1mTGG/OTIUM-UNIQUE.jpg",
    price: 720,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el57",
    name: "RELAX-ТОНИК ДЛЯ КОЖИ ГОЛОВЫ OTIUM UNIQUE, 100 МЛ",
    img: "https://i.ibb.co/vwNkshv/RELAX-OTIUM-UNIQUE.jpg",
    price: 600,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el58",
    name: "ТОНИК ОТ ПЕРХОТИ OTIUM UNIQUE, 100 МЛ",
    img: "https://i.ibb.co/WgHx6Wm/OTIUM-UNIQUE.jpg",
    price: 600,
    quantity: 1,
    productType: "care",
  },
  //СЕРИЯ OTIUM VOLUME (ОТИУМ ВОЛЮМ) ДЛЯ ОБЪЁМА ВОЛОС - #6
  {
    id: "el59",
    name: "НАБОР OTIUM VOLUME",
    img: "https://i.ibb.co/qRMggpd/OTIUM-VOLUME.png",
    price: 790,
    quantity: 1,
    productType: "set",
  },
  {
    id: "el60",
    name: "ШАМПУНЬ ДЛЯ ОБЪЁМА ЖИРНЫХ ВОЛОС OTIUM VOLUME, 250 МЛ",
    img: "https://i.ibb.co/MSRRxmX/OTIUM-VOLUME.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el61",
    name: "ШАМПУНЬ ДЛЯ ОБЪЁМА СУХИХ ВОЛОС OTIUM VOLUME, 250 МЛ",
    img: "https://i.ibb.co/8dg3Twf/OTIUM-VOLUME.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el62",
    name: "ЛЕГКИЙ БАЛЬЗАМ ДЛЯ ОБЪЁМА ВОЛОС OTIUM VOLUME, 200 МЛ",
    img: "https://i.ibb.co/sCqNQYd/OTIUM-VOLUME.jpg",
    price: 495,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el63",
    name: 'СПРЕЙ-УХОД ДЛЯ ВОЛОС "ВОЗДУШНЫЙ ОБЪЁМ" OTIUM VOLUME, 200 МЛ',
    img: "https://i.ibb.co/r0m2YtS/OTIUM-VOLUME.jpg",
    price: 495,
    quantity: 1,
    productType: "styling",
  },
  //СЕРИЯ OTIUM WAVE TWIST (ОТИУМ ВЭЙВ ТВИСТ) ДЛЯ ВЬЮЩИХСЯ ВОЛОС - #7
  {
    id: "el64",
    name: "НАБОР OTIUM WAVE TWIST",
    img: "https://i.ibb.co/v14rgR6/OTIUM-WAVE-TWIST.png",
    price: 790,
    quantity: 1,
    productType: "set",
  },
  {
    id: "el65",
    name: "ШАМПУНЬ ДЛЯ ВЬЮЩИХСЯ ВОЛОС OTIUM WAVE TWIST, 250 МЛ",
    img: "https://i.ibb.co/VTjRHtp/OTIUM-WAVE-TWIST.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el66",
    name: "БАЛЬЗАМ-КОНДИЦИОНЕР ДЛЯ ВЬЮЩИХСЯ ВОЛОС OTIUM WAVE TWIST, 200 МЛ",
    img: "https://i.ibb.co/MGb6HZ2/OTIUM-WAVE-TWIST.jpg",
    price: 495,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el67",
    name: 'СПРЕЙ ДЛЯ ВОЛОС "ЛЁГКОЕ РАСЧЁСЫВАНИЕ" OTIUM WAVE TWIST, 200 МЛ',
    img: "https://i.ibb.co/N2pmzrJ/OTIUM-WAVE-TWIST.jpg",
    price: 475,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el68",
    name: 'ВВ-КРЕМ ДЛЯ ВОЛОС "ПОСЛУШНЫЕ ЛОКОНЫ" OTIUM WAVE TWIST, 100 МЛ',
    img: "https://i.ibb.co/pJGtZqM/OTIUM-WAVE-TWIST.jpg",
    price: 475,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el69",
    name: "КРЕМ-МАСКА ДЛЯ ВЬЮЩИХСЯ ВОЛОС OTIUM WAVE TWIST, 300 МЛ",
    img: "https://i.ibb.co/Xt9TTfs/OTIUM-WAVE-TWIST.jpg",
    price: 710,
    quantity: 1,
    productType: "mask",
  },
  //СТАЙЛИНГ AIREX (АЙРЕКС)
  {
    id: "el70",
    name: "УВЛАЖНЯЮЩИЙ ДВУХФАЗНЫЙ БАЗОВЫЙ ТОНИК ДЛЯ ВОЛОС AIREX, 400 МЛ",
    img: "https://i.ibb.co/r0FzwwX/AIREX.jpg",
    price: 560,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el71",
    name: "УКРЕПЛЯЮЩИЙ ДВУХФАЗНЫЙ БАЗОВЫЙ ТОНИК ДЛЯ ВОЛОС AIREX, 400 МЛ",
    img: "https://i.ibb.co/Svr55zh/AIREX.jpg",
    price: 560,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el72",
    name: "ВИТАМИННЫЙ ДВУХФАЗНЫЙ БАЗОВЫЙ ТОНИК ДЛЯ ВОЛОС AIREX, 400 МЛ",
    img: "https://i.ibb.co/JKP6zF2/AIREX.jpg",
    price: 560,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el73",
    name: "PUSH-UP СПРЕЙ ДЛЯ ПРИКОРНЕВОГО ОБЪЕМА ВОЛОС СИЛЬНОЙ ФИКСАЦИИ AIREX, 100 МЛ",
    img: "https://i.ibb.co/sj1TY4B/PUSH-UP-AIREX.jpg",
    price: 280,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el74",
    name: "ЛАК ДЛЯ ВОЛОС ЭКСТРАСИЛЬНОЙ ФИКСАЦИИ AIREX, 400 МЛ",
    img: "https://i.ibb.co/nQQXfjB/AIREX.jpg",
    price: 590,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el75",
    name: "ЛАК ДЛЯ ВОЛОС СИЛЬНОЙ ФИКСАЦИИ AIREX, 400 МЛ",
    img: "https://i.ibb.co/DCY59Nz/AIREX.jpg",
    price: 590,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el76",
    name: "ЛАК ДЛЯ ВОЛОС ЭЛАСТИЧНОЙ ФИКСАЦИИ AIREX, 400 МЛ",
    img: "https://i.ibb.co/PWKkZys/AIREX.png",
    price: 590,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el77",
    name: "МУСС ДЛЯ ВОЛОС СИЛЬНОЙ ФИКСАЦИИ AIREX, 400 МЛ",
    img: "https://i.ibb.co/zXnwV80/AIREX.jpg",
    price: 590,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el78",
    name: "МУСС ДЛЯ ВОЛОС НОРМАЛЬНОЙ ФИКСАЦИИ AIREX, 400 МЛ",
    img: "https://i.ibb.co/MRnvmRg/AIREX.png",
    price: 590,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el79",
    name: "МУСС ДЛЯ СОЗДАНИЯ ЛОКОНОВ СИЛЬНОЙ ФИКСАЦИИ AIREX, 400 МЛ",
    img: "https://i.ibb.co/fHw02hY/AIREX.png",
    price: 590,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el80",
    name: "БРИЛЛИАНТОВЫЙ БЛЕСК ДЛЯ ВОЛОС AIREX, 300 МЛ",
    img: "https://i.ibb.co/LQt7dZN/AIREX.png",
    price: 485,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el81",
    name: "МОЛОЧКО ДЛЯ УКЛАДКИ ВОЛОС AIREX, 250 МЛ",
    img: "https://i.ibb.co/PD0tsdr/AIREX.jpg",
    price: 375,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el82",
    name: "СПРЕЙ-ТЕРМОЗАЩИТА ЛЕГКОЙ ФИКСАЦИИ AIREX",
    img: "https://i.ibb.co/ZTpD5nN/AIREX.jpg",
    price: 465,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el83",
    name: "ГЕЛЬ ДЛЯ УКЛАДКИ ВОЛОС НОРМАЛЬНОЙ ФИКСАЦИИ AIREX, 200 МЛ",
    img: "https://i.ibb.co/cvgC2Vq/AIREX.jpg",
    price: 315,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el84",
    name: "ГЕЛЬ ДЛЯ УКЛАДКИ ВОЛОС СИЛЬНОЙ ФИКСАЦИИ AIREX, 200 МЛ",
    img: "https://i.ibb.co/cvgC2Vq/AIREX.jpg",
    price: 315,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el85",
    name: "МОДЕЛИРУЮЩИЙ КРЕМ ДЛЯ ВОЛОС 3D-HAIRS AIREX, 150 МЛ",
    img: "https://i.ibb.co/zGspxmQ/3-D-HAIRS-AIREX.png",
    price: 375,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el86",
    name: "ВОСК ДЛЯ МОДЕЛИРОВАНИЯ ВОЛОС AIREX, 75 МЛ",
    img: "https://i.ibb.co/zGspxmQ/3-D-HAIRS-AIREX.png",
    price: 375,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el87",
    name: "STRETCH-ГЕЛЬ ДЛЯ ПЛАСТИЧНОЙ ФИКСАЦИИ ВОЛОС AIREX, 65 МЛ",
    img: "https://i.ibb.co/TTb3jQ6/STRETCH-AIREX.jpg",
    price: 375,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el88",
    name: "ЭЛАСТИК-ГЕЛЬ ДЛЯ МОДЕЛИРОВАНИЯ ВОЛОС AIREX",
    img: "https://i.ibb.co/4ZywRgH/AIREX.jpg",
    price: 375,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el89",
    name: "ГЛИНА ДЛЯ МОДЕЛИРОВАНИЯ ВОЛОС С МАТОВЫМ ЭФФЕКТОМ AIREX, 65 МЛ",
    img: "https://i.ibb.co/hXtGKHm/AIREX.jpg",
    price: 375,
    quantity: 1,
    productType: "styling",
  },
  //СТАЙЛИНГ HAUTE COUTURE (ОТ КУТЮР)
  {
    id: "el90",
    name: "ГЕЛЬ ДЛЯ УКЛАДКИ С ЭФФЕКТОМ МОКРЫХ ВОЛОС VINYL ESTEL HAUTE COUTURE, 150 МЛ",
    img: "https://i.ibb.co/1r5vKzc/VINYL-ESTEL-HAUTE-COUTURE.jpg",
    price: 650,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el91",
    name: "ГЕЛЬ ДЛЯ УКЛАДКИ ВОЛОС SATEEN ESTEL HAUTE COUTURE, 100 МЛ",
    img: "https://i.ibb.co/Hgn2zGn/SATEEN-ESTEL-HAUTE-COUTURE.jpg",
    price: 550,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el92",
    name: "ТЕКСТУРИРУЮЩАЯ ГЛИНА-СОФТ GABARDINE ESTEL HAUTE COUTURE, 40 МЛ",
    img: "https://i.ibb.co/FhZNJXj/GABARDINE-ESTEL-HAUTE-COUTURE.jpg",
    price: 465,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el93",
    name: "ДВУХФАЗНЫЙ ПРАЙМЕР ДЛЯ ВОЛОС SILK ESTEL HAUTE COUTURE, 400 МЛ",
    img: "https://i.ibb.co/xLb9V55/SILK-ESTEL-HAUTE-COUTURE.jpg",
    price: 910,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el94",
    name: "ЛАК ДЛЯ ВОЛОС УЛЬТРАСИЛЬНОЙ ФИКСАЦИИ ATLAS ESTEL HAUTE COUTURE, 400 МЛ",
    img: "https://i.ibb.co/QjG4ZXY/ATLAS-ESTEL-HAUTE-COUTURE.png",
    price: 790,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el95",
    name: "ЛАК ДЛЯ ВОЛОС СИЛЬНОЙ ФИКСАЦИИ CHIFFON ESTEL HAUTE COUTURE, 400 МЛ",
    img: "https://i.ibb.co/NnTwR4x/CHIFFON-ESTEL-HAUTE-COUTURE.jpg",
    price: 790,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el96",
    name: "ЛАК ДЛЯ ВОЛОС ЭЛАСТИЧНОЙ ФИКСАЦИИ JERSEY ESTEL HAUTE COUTURE, 400 МЛ",
    img: "https://i.ibb.co/HXpv2wW/JERSEY-ESTEL-HAUTE-COUTURE.png",
    price: 790,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el97",
    name: "МУСС ДЛЯ ВОЛОС СИЛЬНОЙ ФИКСАЦИИ CACHEMIRE ESTEL HAUTE COUTURE, 300 МЛ",
    img: "https://i.ibb.co/nLhsq0n/CACHEMIRE-ESTEL-HAUTE-COUTURE.jpg",
    price: 790,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el98",
    name: "СПРЕЙ-МУСС ДЛЯ ПРИКОРНЕВОГО ОБЪЁМА ORGANZA ESTEL HAUTE COUTURE, 250 МЛ",
    img: "https://i.ibb.co/Q8xrQ2s/ORGANZA-ESTEL-HAUTE-COUTURE.jpg",
    price: 680,
    quantity: 1,
    productType: "styling",
  },
  //1111111
  {
    id: "el99",
    name: "МУСС ДЛЯ СОЗДАНИЯ ЛОКОНОВ BOUCLE ESTEL HAUTE COUTURE, 250 МЛ",
    img: "https://i.ibb.co/XSz8XMt/BOUCLE-ESTEL-HAUTE-COUTURE.jpg",
    price: 680,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el100",
    name: "БРИЛЛИАНТОВЫЙ БЛЕСК ДЛЯ ВОЛОС LATEX ESTEL HAUTE COUTURE, 300 МЛ",
    img: "https://i.ibb.co/qpzZcnw/LATEX-ESTEL-HAUTE-COUTURE.jpg",
    price: 510,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el101",
    name: "ТЕКСТУРИРУЮЩИЙ СПРЕЙ ДЛЯ ВОЛОС TAFFETA ESTEL HAUTE COUTURE, 300 МЛ",
    img: "https://i.ibb.co/4pPdZXg/TAFFETA-ESTEL-HAUTE-COUTURE.jpg",
    price: 550,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el102",
    name: "СПРЕЙ-ТЕРМОЗАЩИТА ДЛЯ ВОЛОС BATISTE ESTEL HAUTE COUTURE, 300 мл",
    img: "https://i.ibb.co/HHjwx8S/BATISTE-ESTEL-HAUTE-COUTURE.jpg",
    price: 690,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el103",
    name: "СПРЕЙ ДЛЯ ОБЛЕГЧЕНИЯ РАСЧЕСЫВАНИЯ ВОЛОС VELVET ESTEL HAUTE COUTURE, 300 МЛ",
    img: "https://i.ibb.co/W2v4Srm/VELVET-ESTEL-HAUTE-COUTURE.jpg",
    price: 550,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el104",
    name: "КРЕАТИВ-ГЕЛЬ ДЛЯ УКЛАДКИ ВОЛОС DUBLERIN ESTEL HAUTE COUTURE, 100 МЛ",
    img: "https://i.ibb.co/3NrZMkx/DUBLERIN-ESTEL-HAUTE-COUTURE.jpg",
    price: 650,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el105",
    name: "СПРЕЙ-ВОСК ДЛЯ МОДЕЛИРОВАНИЯ ВОЛОС VELOUR ESTEL HAUTE COUTURE, 100 МЛ",
    img: "https://i.ibb.co/CVqSBLK/VELOUR-ESTEL-HAUTE-COUTURE.jpg",
    price: 510,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el106",
    name: "МОДЕЛИРУЮЩАЯ ПАСТА-КРЕМ ДЛЯ ВОЛОС MARCELLINE ESTEL HAUTE COUTURE, 40 МЛ",
    img: "https://i.ibb.co/f1xQsMv/MARCELLINE-ESTEL-HAUTE-COUTURE.jpg",
    price: 465,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el107",
    name: "ПУДРА ДЛЯ СОЗДАНИЯ ОБЪЁМА ВОЛОС MOIRE ESTEL HAUTE COUTURE, 8 Г",
    img: "https://i.ibb.co/gZZg9rw/MOIRE-ESTEL-HAUTE-COUTURE.jpg",
    price: 390,
    quantity: 1,
    productType: "styling",
  },
  //НАБОР ДЛЯ ПРОЦЕДУРЫ ESTEL MON PLAISIR
  {
    id: "el108",
    name: "НАБОР ДЛЯ ПРОЦЕДУРЫ ESTEL MON PLAISIR",
    img: "https://i.ibb.co/y8tfvkb/ESTEL-MON-PLAISIR.jpg",
    price: 3340,
    quantity: 1,
    productType: "set",
  },
  //ALPHA MARINE - НОВАЯ МУЖСКАЯ КОЛЛЕКЦИЯ
  {
    id: "el109",
    name: "OCEAN-ШАМПУНЬ ДЛЯ ВОЛОС ALPHA MARINE, 250 МЛ",
    img: "https://i.ibb.co/0GS4T5Y/OCEAN-ALPHA-MARINE.png",
    price: 520,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el110",
    name: "OCEAN-ШАМПУНЬ ДЛЯ ВОЛОС ALPHA MARINE, 1000 МЛ",
    img: "https://i.ibb.co/0fm22z8/OCEAN-ALPHA-MARINE-1000.png",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el111",
    name: "SLIDE-ГЕЛЬ ДЛЯ ВОЛОС УЛЬТРАСИЛЬНАЯ ФИКСАЦИЯ ALPHA MARINE, 100 МЛ",
    img: "https://i.ibb.co/THbGH7C/SLIDE-ALPHA-MARINE.png",
    price: 360,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el112",
    name: "SALT-ПАСТА ДЛЯ ВОЛОС С МАТОВЫМ ЭФФЕКТОМ ALPHA MARINE, 100 МЛ",
    img: "https://i.ibb.co/kKwbKR8/SALT-ALPHA-MARINE.png",
    price: 360,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el113",
    name: "HYDROBOOST-СЫВОРОТКА ДЛЯ ЛИЦА ALPHA MARINE, 50 МЛ",
    img: "https://i.ibb.co/1ZFrRJm/HYDROBOOST-ALPHA-MARINE.png",
    price: 890,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el114",
    name: "FLUID-ГЕЛЬ ДЛЯ КОЖИ ВОКРУГ ГЛАЗ ALPHA MARINE, 15 МЛ",
    img: "https://i.ibb.co/ggp9ZNJ/FLUID-ALPHA-MARINE.png",
    price: 520,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el115",
    name: "SHARK-ПАСТА ЗУБНАЯ ALPHA MARINE, 90 МЛ",
    img: "https://i.ibb.co/p11Jhnq/SHARK-ALPHA-MARINE.png",
    price: 265,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el116",
    name: "SURF-БАЛЬЗАМ ДЛЯ ГУБ ALPHA MARINE, 10 МЛ",
    img: "https://i.ibb.co/RbJvdMQ/SURF-ALPHA-MARINE.png",
    price: 265,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el117",
    name: "GLISSER-ГЕЛЬ ДЛЯ БРИТЬЯ ALPHA MARINE, 100 МЛ",
    img: "https://i.ibb.co/0Kcx9DL/GLISSER-ALPHA-MARINE.png",
    price: 360,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el118",
    name: "STORM-ЛОСЬОН ПОСЛЕ БРИТЬЯ ALPHA MARINE, 100 МЛ",
    img: "https://i.ibb.co/Vwh2WrS/STORM-ALPHA-MARINE.png",
    price: 450,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el119",
    name: "DIVE-ГЕЛЬ ДЛЯ ДУША ALPHA MARINE, 200 МЛ",
    img: "https://i.ibb.co/bgx8RFQ/DIVE-ALPHA-MARINE.png",
    price: 430,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el120",
    name: "DEEP-АНТИПЕРСПИРАНТ ДЛЯ ТЕЛА ALPHA MARINE, 50 МЛ",
    img: "https://i.ibb.co/bXxYtfN/DEEP-ALPHA-MARINE.png",
    price: 410,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el121",
    name: "FORT-БАЛЬЗАМ ДЛЯ РУК ALPHA MARINE, 90 МЛ",
    img: "https://i.ibb.co/tmGfpCQ/FORT-ALPHA-MARINE.png",
    price: 265,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el122",
    name: "ПАРФЮМЕРНАЯ ВОДА ALPHA MARINE, 50 МЛ",
    img: "https://i.ibb.co/gPmk5VW/ALPHA-MARINE.png",
    price: 4500,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el123",
    name: "НАБОР FRESH SPLASH ALPHA MARINE",
    img: "https://i.ibb.co/qx0bQwN/FRESH-SPLASH-ALPHA-MARINE.jpg",
    price: 1100,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el124",
    name: "ПАРФЮМЕРНЫЙ НАБОР ALPHA MARINE",
    img: "https://i.ibb.co/DDDb5hh/ALPHA-MARINE.jpg",
    price: 4175,
    quantity: 1,
    productType: "men",
  },
  {
    id: "el125",
    name: "ВЕЧЕРНИЙ ШАМПУНЬ ДЛЯ ВОЛОС ESTEL MYSTERIA, 250 МЛ",
    img: "https://i.ibb.co/3vM68cD/ESTEL-MYSTERIA.png",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el126",
    name: "ШАМПУНЬ ДЛЯ ВОЛОС ESTEL MYSTERIA, 1000 МЛ",
    img: "https://i.ibb.co/nRPT96G/ESTEL-MYSTERIA-1000.png",
    price: 900,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el127",
    name: "НОЧНАЯ КРЕМ-МАСКА ДЛЯ ВОЛОС ESTEL MYSTERIA, 100 МЛ",
    img: "https://i.ibb.co/CBBzVhg/ESTEL-MYSTERIA.png",
    price: 495,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el128",
    name: "ДВУХФАЗНЫЙ УТРЕННИЙ СПРЕЙ ДЛЯ ВОЛОС ESTEL MYSTERIA, 100 МЛ",
    img: "https://i.ibb.co/D5q931x/ESTEL-MYSTERIA.png",
    price: 360,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el129",
    name: "ВЕЧЕРНЯЯ ГЕЛЬ-ПЕНА ДЛЯ ДУША И ВАННЫ ESTEL MYSTERIA, 200 МЛ",
    img: "https://i.ibb.co/C6ZHYZk/ESTEL-MYSTERIA.png",
    price: 450,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el130",
    name: "ВЕЧЕРНЕЕ МОЛОЧКО ДЛЯ ТЕЛА ESTEL MYSTERIA, 150 МЛ",
    img: "https://i.ibb.co/x2rrqLT/ESTEL-MYSTERIA.png",
    price: 430,
    quantity: 1,
    productType: "care",
  },
  {
    id: "el131",
    name: "ПАРФЮМЕРНЫЙ НАБОР ESTEL MYSTERIA",
    img: "https://i.ibb.co/pLzhGXH/ESTEL-MYSTERIA.png",
    price: 3675,
    quantity: 1,
    productType: "set",
  },
  {
    id: "el132",
    name: "ПАРФЮМЕРНЫЕ КОМПАНЬОНЫ ESTEL MYSTERIA",
    img: "https://i.ibb.co/M6gL1fz/ESTEL-MYSTERIA.png",
    price: 990,
    quantity: 1,
    productType: "other",
  },
  {
    id: "el133",
    name: "ПАРФЮМЕРНАЯ КОЛЛЕКЦИЯ ESTEL MYSTERIA",
    img: "https://i.ibb.co/602pmrd/ESTEL-MYSTERIA.png",
    price: 1600,
    quantity: 1,
    productType: "other",
  },
  //MOLODO ZELENO - ОРГАНИЧЕСКАЯ СЕРИЯ ДЛЯ ВОЛОС С ХЛОРОФИЛЛОМ
  {
    id: "el134",
    name: "НАБОР ДЛЯ ПРОЦЕДУРЫ MOLODO ZELENO",
    img: "https://i.ibb.co/cxfxVLK/MOLODO-ZELENO.png",
    price: 2250,
    quantity: 1,
    productType: "set",
  },
  {
    id: "el135",
    name: "ЭЛИКСИР-БАЛЬЗАМ С ХЛОРОФИЛЛОМ ДЛЯ ВОЛОС MOLODO ZELENO, 200 МЛ",
    img: "https://i.ibb.co/XtWFBCG/MOLODO-ZELENO.png",
    price: 520,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el136",
    name: "ЭЛИКСИР-БАЛЬЗАМ С ХЛОРОФИЛЛОМ ДЛЯ ВОЛОС MOLODO ZELENO, 400 МЛ",
    img: "https://i.ibb.co/7kPqvbt/MOLODO-ZELENO-400.png",
    price: 750,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el137",
    name: "ШАМПУНЬ С ХЛОРОФИЛЛОМ ДЛЯ ВОЛОС MOLODO ZELENO, 250 МЛ",
    img: "https://i.ibb.co/jgHbTTT/MOLODO-ZELENO.png",
    price: 520,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el138",
    name: "ГЕЛЬ ДЛЯ ДУША С ХЛОРОФИЛЛОМ MOLODO ZELENO, 200 МЛ",
    img: "https://i.ibb.co/gZvvrP8/MOLODO-ZELENO.png",
    price: 450,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el139",
    name: "МАСКА-УВЛАЖНЕНИЕ С ХЛОРОФИЛЛОМ ДЛЯ ЛИЦА MOLODO ZELENO, 100 МЛ",
    img: "https://i.ibb.co/GsbKwct/MOLODO-ZELENO.png",
    price: 630,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el140",
    name: "МИСТ ДЛЯ ЛИЦА «ЖИВАЯ ВОДА» С ХЛОРОФИЛЛОМ MOLODO ZELENO, 100 МЛ",
    img: "https://i.ibb.co/SJ4jRYN/MOLODO-ZELENO.png",
    price: 470,
    quantity: 1,
    productType: "other",
  },
  //BABAYAGA - ВОССТАНАВЛИВАЮЩАЯ ЯГОДНАЯ СЕРИЯ
  {
    id: "el141",
    name: "ВОССТАНАВЛИВАЮЩИЙ ЯГОДНЫЙ ШАМПУНЬ BABAYAGA, 250 МЛ",
    img: "https://i.ibb.co/5RH4k9p/BABAYAGA.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el142",
    name: "ВОССТАНАВЛИВАЮЩИЙ ЯГОДНЫЙ ШАМПУНЬ BABAYAGA, 1000 МЛ",
    img: "https://i.ibb.co/2ZV8Vr6/BABAYAGA-1000.jpg",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el143",
    name: "ВОССТАНАВЛИВАЮЩИЙ ЯГОДНЫЙ БАЛЬЗАМ BABAYAGA, 1000 МЛ",
    img: "https://i.ibb.co/9Tqy85C/BABAYAGA-1000.jpg",
    price: 1200,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el144",
    name: "ВОССТАНАВЛИВАЮЩАЯ ЯГОДНАЯ МАСКА BABAYAGA, 200 МЛ",
    img: "https://i.ibb.co/fX3VNrg/BABAYAGA.jpg",
    price: 495,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el145",
    name: "СПРЕЙ-ТЕРМОЗАЩИТА BABAYAGA, 200 МЛ",
    img: "https://i.ibb.co/LhLL64d/BABAYAGA.jpg",
    price: 495,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el146",
    name: "НАБОР BABAYAGA",
    img: "https://i.ibb.co/sKT1WC9/BABAYAGA.jpg",
    price: 1150,
    quantity: 1,
    productType: "set",
  },
  //KIKIMORA - УЛЬТРАУВЛАЖНЯЮЩАЯ ТОРФЯНАЯ СЕРИЯ
  {
    id: "el147",
    name: "УЛЬТРАУВЛАЖНЯЮЩИЙ ТОРФЯНОЙ ШАМПУНЬ KIKIMORA, 250 МЛ",
    img: "https://i.ibb.co/RH2K6k2/KIKIMORA.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el148",
    name: "УЛЬТРАУВЛАЖНЯЮЩИЙ ТОРФЯНОЙ ШАМПУНЬ KIKIMORA, 1000 МЛ",
    img: "https://i.ibb.co/G097MvX/KIKIMORA-1000.jpg",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el149",
    name: "УЛЬТРАУВЛАЖНЯЮЩИЙ ТОРФЯНОЙ БАЛЬЗАМ KIKIMORA, 1000 МЛ",
    img: "https://i.ibb.co/G097MvX/KIKIMORA-1000.jpg",
    price: 1200,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el150",
    name: "УЛЬТРАУВЛАЖНЯЮЩАЯ ТОРФЯНАЯ МАСКА KIKIMORA, 200 МЛ",
    img: "https://i.ibb.co/G097MvX/KIKIMORA-1000.jpg",
    price: 495,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el151",
    name: "РАЗГЛАЖИВАЮЩИЙ ТОРФЯНОЙ КРЕМ-ФИЛЛЕР KIKIMORA, 100 МЛ",
    img: "https://i.ibb.co/G097MvX/KIKIMORA-1000.jpg",
    price: 475,
    quantity: 1,
    productType: "styling",
  },
  {
    id: "el152",
    name: "НАБОР KIKIMORA",
    img: "https://i.ibb.co/VLkDqJ6/KIKIMORA.png",
    price: 1150,
    quantity: 1,
    productType: "set",
  },
  //VEDMA - МОЛОЧНАЯ СЕРИЯ ДЛЯ БЛЕСКА
  {
    id: "el153",
    name: "МОЛОЧНЫЙ БЛЕСК-ШАМПУНЬ VEDMA, 250 МЛ",
    img: "https://i.ibb.co/ZLNMKCR/VEDMA.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el154",
    name: "МОЛОЧНЫЙ БЛЕСК-ШАМПУНЬ VEDMA, 1000 МЛ",
    img: "https://i.ibb.co/1GQvvVP/VEDMA-1000.jpg",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el155",
    name: "МОЛОЧНЫЙ БЛЕСК-БАЛЬЗАМ VEDMA, 1000 МЛ",
    img: "https://i.ibb.co/8x9jhPR/VEDMA.jpg",
    price: 1200,
    quantity: 1,
    productType: "balsam",
  },
  {
    id: "el156",
    name: "МОЛОЧНАЯ БЛЕСК-МАСКА VEDMA, 200",
    img: "https://i.ibb.co/8x9jhPR/VEDMA.jpg",
    price: 495,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el157",
    name: "МАСЛЯНЫЙ ЭЛИКСИР VEDMA, 50 МЛ",
    img: "https://i.ibb.co/Hqjgf7C/VEDMA.jpg",
    price: 475,
    quantity: 1,
    productType: "other",
  },
  {
    id: "el158",
    name: "НАБОР VEDMA",
    img: "https://i.ibb.co/P1qHZGK/VEDMA.png",
    price: 1150,
    quantity: 1,
    productType: "set",
  },
  //ESTEL THERMOKERATIN (ТЕРМОКЕРАТИН)
  {
    id: "el159",
    name: "НАБОР ДЛЯ ПРОЦЕДУРЫ ESTEL THERMOKERATIN",
    img: "https://i.ibb.co/Hz5rh41/ESTEL-THERMOKERATIN.jpg",
    price: 2100,
    quantity: 1,
    productType: "set",
  },
  {
    id: "el160",
    name: "ТЕРМОАКТИВАТОР ESTEL THERMOKERATIN",
    img: "https://i.ibb.co/4Fnm9ZH/ESTEL-THERMOKERATIN.jpg",
    price: 550,
    quantity: 1,
    productType: "other",
  },
  {
    id: "el161",
    name: "КЕРАТИНОВАЯ МАСКА ДЛЯ ВОЛОС ESTEL THERMOKERATIN",
    img: "https://i.ibb.co/P5vjDgC/ESTEL-THERMOKERATIN.jpg",
    price: 1100,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el162",
    name: "КЕРАТИНОВЫЙ ШАМПУНЬ ДЛЯ ВОЛОС ESTEL KERATIN, 250 МЛ",
    img: "https://i.ibb.co/wSVdZVh/ESTEL-KERATIN.jpg",
    price: 495,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el163",
    name: "КЕРАТИНОВЫЙ ШАМПУНЬ ДЛЯ ВОЛОС ESTEL KERATIN. ОБЪЁМ 1000 МЛ",
    img: "https://i.ibb.co/vwcTcfm/ESTEL-KERATIN-1000.jpg",
    price: 1000,
    quantity: 1,
    productType: "shampoo",
  },
  {
    id: "el164",
    name: "КЕРАТИНОВАЯ МАСКА ДЛЯ ВОЛОС ESTEL KERATIN, 250 МЛ",
    img: "https://i.ibb.co/1by5PdN/ESTEL-KERATIN.jpg",
    price: 600,
    quantity: 1,
    productType: "mask",
  },
  {
    id: "el165",
    name: "КЕРАТИНОВАЯ ВОДА ДЛЯ ВОЛОС ESTEL KERATIN, 100 МЛ",
    img: "https://i.ibb.co/gZdq1y8/ESTEL-KERATIN.jpg",
    price: 470,
    quantity: 1,
    productType: "other",
  },
  //УХОД ДЛЯ РУК ESTEL M`USE
  {
    id: "el166",
    name: "ЖИДКОЕ МЫЛО ДЛЯ РУК ESTEL M`USE, 475 МЛ",
    img: "https://i.ibb.co/CtB7kTR/ESTEL-M-USE.png",
    price: 300,
    quantity: 1,
    productType: "other",
  },
  {
    id: "el167",
    name: "УВЛАЖНЯЮЩИЙ КРЕМ ДЛЯ РУК ESTEL M`USE, 100 МЛ",
    img: "https://i.ibb.co/ryPSwTq/ESTEL-M-USE-100.jpg",
    price: 195,
    quantity: 1,
    productType: "cream",
  },
  {
    id: "el168",
    name: "УВЛАЖНЯЮЩИЙ КРЕМ ДЛЯ РУК ESTEL M`USE, 475 МЛ",
    img: "https://i.ibb.co/DRBCYtj/ESTEL-M-USE-475.png",
    price: 550,
    quantity: 1,
    productType: "cream",
  },
  {
    id: "el169",
    name: "ЗАЩИТНЫЙ КРЕМ ДЛЯ РУК ESTEL M`USE, 100 МЛ",
    img: "https://i.ibb.co/MsHgtQb/ESTEL-M-USE-100.png",
    price: 195,
    quantity: 1,
    productType: "cream",
  },
  {
    id: "el170",
    name: "ЗАЩИТНЫЙ КРЕМ ДЛЯ РУК ESTEL M`USE, 475 МЛ",
    img: "https://i.ibb.co/vd0LkBf/ESTEL-M-USE-475.png",
    price: 550,
    quantity: 1,
    productType: "cream",
  },
];

let catalogEpica = [
  //Coloring
  {
    id: "el171",
    name: "Нейтрализующий шампунь POST COLOR с протеинами шелка и кератином 1000 мл",
    img: "https://i.ibb.co/4Z7S5GC/POST-COLOR-1000.webp",
    quantity: 1,
    price: 660,
    productType: "shampoo",
  },
  {
    id: "el172",
    name: "Нейтрализующая маска POST COLOR с протеинами шелка и кератином 1000 мл",
    img: "https://i.ibb.co/pnJnzYP/POST-COLOR-1000.webp",
    quantity: 1,
    price: 825,
    productType: "mask",
  },
  {
    id: "el173",
    name: "«PURE SOLUTION» Шампунь для глубокого очищения с натуральным бетаином 1000 мл",
    img: "https://i.ibb.co/1m1ywBf/PURE-SOLUTION-1000.webp",
    quantity: 1,
    price: 660,
    productType: "shampoo",
  },
  {
    id: "el174",
    name: "Лосьон для удаления краски с кожи 150 мл",
    img: "https://i.ibb.co/x8kZcvH/150.webp",
    quantity: 1,
    price: 230,
    productType: "other",
  },
  //Hair care / AMBER SHINE ORGANIC
  {
    id: "el175",
    name: "Сыворотка для восстановления волос AMBER SHINE ORGANIC с облепиховым маслом и фосфолипидами дикого шафрана 100 мл",
    img: "https://i.ibb.co/PQnj8Vq/AMBER-SHINE-ORGANIC.webp",
    quantity: 1,
    price: 660,
    productType: "styling",
  },
  {
    id: "el176",
    name: "Amber Shine Organic Шампунь для восстановления и питания волос 250 мл",
    img: "https://i.ibb.co/n895yCw/AMBER-SHINE-ORGANIC.webp",
    quantity: 1,
    price: 415,
    productType: "shampoo",
  },
  {
    id: "el177",
    name: "Amber Shine Organic Шампунь для восстановления и питания волос 1000 мл",
    img: "https://i.ibb.co/n895yCw/AMBER-SHINE-ORGANIC.webp",
    quantity: 1,
    price: 900,
    productType: "shampoo",
  },
  {
    id: "el178",
    name: "Amber Shine Organic Кондиционер для восстановления и питания волос 250 мл",
    img: "https://i.ibb.co/n895yCw/AMBER-SHINE-ORGANIC.webp",
    quantity: 1,
    price: 450,
    productType: "balsam",
  },
  {
    id: "el179",
    name: "Amber Shine Organic Кондиционер для восстановления и питания волос 1000 мл",
    img: "https://i.ibb.co/n895yCw/AMBER-SHINE-ORGANIC.webp",
    quantity: 1,
    price: 945,
    productType: "balsam",
  },
  {
    id: "el180",
    name: "Amber Shine Organic Маска для восстановления и питания волос 250 мл",
    img: "https://i.ibb.co/K5M3Y8p/AMBER-SHINE-ORGANIC.webp",
    quantity: 1,
    price: 495,
    productType: "mask",
  },
  {
    id: "el181",
    name: "Amber Shine Organic Маска для восстановления и питания волос 1000 мл",
    img: "https://i.ibb.co/K5M3Y8p/AMBER-SHINE-ORGANIC.webp",
    quantity: 1,
    price: 990,
    productType: "mask",
  },
  //Hair care / AMBER SHINE ORGANIC
  {
    id: "el182",
    name: "Deep Recover Шампунь для восстановления поврежденных волос 300 мл",
    img: "https://i.ibb.co/HHtXw7Y/DEEP-RECOVER.webp",
    quantity: 1,
    price: 330,
    productType: "shampoo",
  },
  {
    id: "el183",
    name: "Deep Recover Шампунь для восстановления поврежденных волос 1000 мл",
    img: "https://i.ibb.co/HHtXw7Y/DEEP-RECOVER.webp",
    quantity: 1,
    price: 660,
    productType: "shampoo",
  },
  {
    id: "el184",
    name: "Deep Recover Кондиционер для восстановления поврежденных волос 300 мл",
    img: "https://i.ibb.co/LPrBrTp/DEEP-RECOVER.webp",
    quantity: 1,
    price: 360,
    productType: "balsam",
  },
  {
    id: "el185",
    name: "Deep Recover Кондиционер для восстановления поврежденных волос 1000 мл",
    img: "https://i.ibb.co/LPrBrTp/DEEP-RECOVER.webp",
    quantity: 1,
    price: 720,
    productType: "balsam",
  },
  {
    id: "el186",
    name: "Deep Recover Маска для восстановления поврежденных волос 250 мл",
    img: "https://i.ibb.co/HPqRbBx/DEEP-RECOVER.webp",
    quantity: 1,
    price: 415,
    productType: "mask",
  },
  {
    id: "el187",
    name: "Deep Recover Маска для восстановления поврежденных волос 1000 мл",
    img: "https://i.ibb.co/HPqRbBx/DEEP-RECOVER.webp",
    quantity: 1,
    price: 825,
    productType: "mask",
  },
  {
    id: "el188",
    name: "Deep Recover Масло для поврежденных волос 100 мл",
    img: "https://i.ibb.co/c8vyd0t/DEEP-RECOVER.webp",
    quantity: 1,
    price: 660,
    productType: "styling",
  },
  //Hair care / HEMP THERAPY ORGANIC
  {
    id: "el189",
    name: "Hemp Therapy Активатор роста волос 100 мл",
    img: "https://i.ibb.co/CV9swks/image.webp",
    quantity: 1,
    price: 660,
    productType: "styling",
  },
  {
    id: "el190",
    name: "Hemp Therapy Пилинг для кожи головы с маслом семян конопли 150 мл",
    img: "https://i.ibb.co/r7cfpNt/Hemp-therapy-ORGANIC.webp",
    quantity: 1,
    price: 600,
    productType: "care",
  },
  {
    id: "el191",
    name: "Hemp Therapy Pro Шампунь для роста волос 250 мл",
    img: "https://i.ibb.co/WP5yN47/HEMP-THERAPY-Organic.webp",
    quantity: 1,
    price: 415,
    productType: "shampoo",
  },
  {
    id: "el192",
    name: "Hemp Therapy Pro Шампунь для роста волос 1000 мл",
    img: "https://i.ibb.co/WP5yN47/HEMP-THERAPY-Organic.webp",
    quantity: 1,
    price: 900,
    productType: "shampoo",
  },
  {
    id: "el193",
    name: "Hemp Therapy Pro Кондиционер для роста волос 250 мл",
    img: "https://i.ibb.co/RPSfQkK/HEMP-THERAPY-Organic.webp",
    quantity: 1,
    price: 450,
    productType: "balsam",
  },
  {
    id: "el194",
    name: "Hemp Therapy Pro Кондиционер для роста волос 1000 мл",
    img: "https://i.ibb.co/RPSfQkK/HEMP-THERAPY-Organic.webp",
    quantity: 1,
    price: 945,
    productType: "balsam",
  },
  //Hair care / SKIN BALANCE
  {
    id: "el195",
    name: "Skin Balance Шампунь регулирующий работу сальных желез 300 мл",
    img: "https://i.ibb.co/D1DDf8L/SKIN-BALANCE.webp",
    quantity: 1,
    price: 330,
    productType: "shampoo",
  },
  {
    id: "el196",
    name: "Skin Balance Шампунь регулирующий работу сальных желез 1000 мл",
    img: "https://i.ibb.co/D1DDf8L/SKIN-BALANCE.webp",
    quantity: 1,
    price: 660,
    productType: "shampoo",
  },
  {
    id: "el197",
    name: "Skin Balance Кондиционер регулирующий работу сальных желез 300 мл",
    img: "https://i.ibb.co/YDyTCnz/SKIN-BALANCE.webp",
    quantity: 1,
    price: 360,
    productType: "balasm",
  },
  {
    id: "el198",
    name: "Skin Balance Кондиционер регулирующий работу сальных желез 1000 мл",
    img: "https://i.ibb.co/YDyTCnz/SKIN-BALANCE.webp",
    quantity: 1,
    price: 720,
    productType: "balasm",
  },
  //Hair care / VOLUME BOOSTER
  {
    id: "el199",
    name: "Volume Booster Шампунь для объема волос 300 мл",
    img: "https://i.ibb.co/R6wMMFJ/Volume-booster.webp",
    quantity: 1,
    price: 330,
    productType: "shampoo",
  },
  {
    id: "el200",
    name: "Volume Booster Шампунь для объема волос 1000 мл",
    img: "https://i.ibb.co/R6wMMFJ/Volume-booster.webp",
    quantity: 1,
    price: 660,
    productType: "shampoo",
  },
  {
    id: "el201",
    name: "Volume Booster Кондиционер для объема волос 300 мл",
    img: "https://i.ibb.co/k8Cpc1s/Volume-booster.webp",
    quantity: 1,
    price: 360,
    productType: "balasm",
  },
  {
    id: "el202",
    name: "Volume Booster Кондиционер для объема волос 1000 мл",
    img: "https://i.ibb.co/k8Cpc1s/Volume-booster.webp",
    quantity: 1,
    price: 720,
    productType: "balasm",
  },
  //Hair care / INTENSE MOISTURE
  {
    id: "el203",
    name: "Intense Moisture Шампунь для увлажнения и питания сухих волос 300 мл",
    img: "https://i.ibb.co/zXBYxC1/INTENSE-MOISTURE.webp",
    quantity: 1,
    price: 330,
    productType: "shampoo",
  },
  {
    id: "el204",
    name: "Intense Moisture Шампунь для увлажнения и питания сухих волос 1000 мл",
    img: "https://i.ibb.co/zXBYxC1/INTENSE-MOISTURE.webp",
    quantity: 1,
    price: 660,
    productType: "shampoo",
  },
  {
    id: "el205",
    name: "Intense Moisture Кондиционер для увлажнения и питания сухих волос 300 мл",
    img: "https://i.ibb.co/qy2vXHz/INTENSE-MOISTURE.webp",
    quantity: 1,
    price: 360,
    productType: "balasm",
  },
  {
    id: "el206",
    name: "Intense Moisture Кондиционер для увлажнения и питания сухих волос 1000 мл",
    img: "https://i.ibb.co/qy2vXHz/INTENSE-MOISTURE.webp",
    quantity: 1,
    price: 720,
    productType: "balasm",
  },
  {
    id: "el207",
    name: "Intense Moisture Маска для увлажнения и питания сухих волос 250 мл",
    img: "https://i.ibb.co/TBRqm0z/INTENSE-MOISTURE.webp",
    quantity: 1,
    price: 415,
    productType: "mask",
  },
  {
    id: "el208",
    name: "Intense Moisture Маска для увлажнения и питания сухих волос 1000 мл",
    img: "https://i.ibb.co/TBRqm0z/INTENSE-MOISTURE.webp",
    quantity: 1,
    price: 825,
    productType: "mask",
  },
  //Hair care / RICH COLOR
  {
    id: "el209",
    name: "Rich Color Шампунь для окрашенных волос 300 мл",
    img: "https://i.ibb.co/4f617nm/RICH-COLOR.webp",
    quantity: 1,
    price: 330,
    productType: "shampoo",
  },
  {
    id: "el210",
    name: "Rich Color Шампунь для окрашенных волос 1000 мл",
    img: "https://i.ibb.co/4f617nm/RICH-COLOR.webp",
    quantity: 1,
    price: 660,
    productType: "shampoo",
  },
  {
    id: "el211",
    name: "Rich Color Шампунь для окрашенных волос 5000 мл",
    img: "https://i.ibb.co/4f617nm/RICH-COLOR.webp",
    quantity: 1,
    price: 1875,
    productType: "shampoo",
  },
  {
    id: "el212",
    name: "Rich Color Маска для окрашенных волос 250 мл",
    img: "https://i.ibb.co/dPTdWYs/RICH-COLOR.webp",
    quantity: 1,
    price: 415,
    productType: "balasm",
  },
  {
    id: "el213",
    name: "Rich Color Маска для окрашенных волос 1000 мл",
    img: "https://i.ibb.co/dPTdWYs/RICH-COLOR.webp",
    quantity: 1,
    price: 825,
    productType: "balasm",
  },
  {
    id: "el214",
    name: "Rich Color Маска для окрашенных волос 250 мл",
    img: "https://i.ibb.co/LYxbrBK/RICH-COLOR.webp",
    quantity: 1,
    price: 415,
    productType: "mask",
  },
  {
    id: "el215",
    name: "Rich Color Маска для окрашенных волос 1000 мл",
    img: "https://i.ibb.co/LYxbrBK/RICH-COLOR.webp",
    quantity: 1,
    price: 825,
    productType: "mask",
  },
  //Hair care / ANTI-DANDRUFF
  {
    id: "el216",
    name: "Anti-Dandruff Шампунь против перхоти 300 мл",
    img: "https://i.ibb.co/DzBSFkn/ANTI-DANDRUFF.webp",
    quantity: 1,
    price: 415,
    productType: "shampoo",
  },
  //Hair care / MEN`S
  {
    id: "el217",
    name: "For Men Мужской шампунь с кондиционирующим эффектом 250 мл",
    img: "https://i.ibb.co/kh1fH5p/image.webp",
    quantity: 1,
    price: 390,
    productType: "shampoo",
  },
  {
    id: "el218",
    name: "For Men Мужской шампунь с кондиционирующим эффектом 1000 мл",
    img: "https://i.ibb.co/kh1fH5p/image.webp",
    quantity: 1,
    price: 780,
    productType: "shampoo",
  },
  {
    id: "el219",
    name: "For Men 3 in 1 Мужской шампунь, гель для душа и кондиционер с охлаждающим эффектом 250 мл",
    img: "https://i.ibb.co/LSJCdb1/image.webp",
    quantity: 1,
    price: 390,
    productType: "balsam",
  },
  {
    id: "el220",
    name: "For Men 3 in 1 Мужской шампунь, гель для душа и кондиционер с охлаждающим эффектом 1000 мл",
    img: "https://i.ibb.co/LSJCdb1/image.webp",
    quantity: 1,
    price: 780,
    productType: "balsam",
  },
  //Hair care / KERATIN PRO
  {
    id: "el221",
    name: "Keratin Pro Шампунь для реконструкции волос 250 мл",
    img: "https://i.ibb.co/jvGGfyH/Keratin-PRO.webp",
    quantity: 1,
    price: 415,
    productType: "shampoo",
  },
  {
    id: "el222",
    name: "Keratin Pro Шампунь для реконструкции волос 1000 мл",
    img: "https://i.ibb.co/jvGGfyH/Keratin-PRO.webp",
    quantity: 1,
    price: 900,
    productType: "shampoo",
  },
  {
    id: "el223",
    name: "Keratin Pro Маска для реконструкции волос 250 мл",
    img: "https://i.ibb.co/khphgcp/Keratin-PRO.webp",
    quantity: 1,
    price: 495,
    productType: "balsam",
  },
  {
    id: "el224",
    name: "Keratin Pro Маска для реконструкции волос 1000 мл",
    img: "https://i.ibb.co/khphgcp/Keratin-PRO.webp",
    quantity: 1,
    price: 990,
    productType: "balsam",
  },
  {
    id: "el225",
    name: "Keratin Pro Маска для реконструкции волос 250 мл",
    img: "https://i.ibb.co/HK378Gw/Keratin-PRO.webp",
    quantity: 1,
    price: 495,
    productType: "mask",
  },
  {
    id: "el226",
    name: "Keratin Pro Маска для реконструкции волос 1000 мл",
    img: "https://i.ibb.co/HK378Gw/Keratin-PRO.webp",
    quantity: 1,
    price: 990,
    productType: "mask",
  },
  {
    id: "el227",
    name: "Keratin Pro Спрей для реконструкции волос 250 мл",
    img: "https://i.ibb.co/Lh18ksr/Keratin-PRO.webp",
    quantity: 1,
    price: 660,
    productType: "styling",
  },
  //Hair care / COLLAGEN PRO
  {
    id: "el228",
    name: "Collagen Pro Кондиционер для увлажнения и реконструкции волос 250 мл",
    img: "https://i.ibb.co/8B8ChwP/COLLAGEN-PRO.webp",
    quantity: 1,
    price: 450,
    productType: "balsam",
  },
  {
    id: "el229",
    name: "Collagen Pro Кондиционер для увлажнения и реконструкции волос 1000 мл",
    img: "https://i.ibb.co/8B8ChwP/COLLAGEN-PRO.webp",
    quantity: 1,
    price: 945,
    productType: "balsam",
  },
  {
    id: "el230",
    name: "Collagen Pro Шампунь для увлажнения и реконструкции волос 250 мл",
    img: "https://i.ibb.co/qg70Sk0/COLLAGEN-PRO.webp",
    quantity: 1,
    price: 415,
    productType: "shampoo",
  },
  {
    id: "el231",
    name: "Collagen Pro Шампунь для увлажнения и реконструкции волос 1000 мл",
    img: "https://i.ibb.co/qg70Sk0/COLLAGEN-PRO.webp",
    quantity: 1,
    price: 900,
    productType: "shampoo",
  },
  //Hair care / SILK WAVES
  {
    id: "el232",
    name: "Silk Waves Шампунь для вьющихся и кудрявых волос 300 мл",
    img: "https://i.ibb.co/CWN2RdL/SILK-WAVES.webp",
    quantity: 1,
    price: 330,
    productType: "styling",
  },
  {
    id: "el233",
    name: "Silk Waves Шампунь для вьющихся и кудрявых волос 1000 мл",
    img: "https://i.ibb.co/CWN2RdL/SILK-WAVES.webp",
    quantity: 1,
    price: 660,
    productType: "styling",
  },
  {
    id: "el234",
    name: "Silk Waves Кондиционер для вьющихся и кудрявых волос 300 мл",
    img: "https://i.ibb.co/RSgp8v2/SILK-WAVES.webp",
    quantity: 1,
    price: 360,
    productType: "balsam",
  },
  {
    id: "el235",
    name: "Silk Waves Кондиционер для вьющихся и кудрявых волос 1000 мл",
    img: "https://i.ibb.co/RSgp8v2/SILK-WAVES.webp",
    quantity: 1,
    price: 720,
    productType: "balsam",
  },
  //Hair care / DELICATE
  {
    id: "el236",
    name: "Delicate Шампунь бессульфатный для деликатного очищения волос 300 мл",
    img: "https://i.ibb.co/BPXs0fc/DELICATE.webp",
    quantity: 1,
    price: 495,
    productType: "shampoo",
  },
  {
    id: "el237",
    name: "Delicate Шампунь бессульфатный для деликатного очищения волос 1000 мл",
    img: "https://i.ibb.co/BPXs0fc/DELICATE.webp",
    quantity: 1,
    price: 975,
    productType: "shampoo",
  },
  //Hand care
  {
    id: "el238",
    name: "Cream Soap Regenerating Крем-мыло регенерирующее 400 мл",
    img: "https://i.ibb.co/sj9qjVJ/image.png",
    quantity: 1,
    price: 300,
    productType: "other",
  },
  {
    id: "el239",
    name: "Nutritious Крем для рук питательный 125 мл",
    img: "https://i.ibb.co/qdH3hqN/image.webp",
    quantity: 1,
    price: 225,
    productType: "cream",
  },
  {
    id: "el240",
    name: "Nutritious Крем для рук питательный 400 мл",
    img: "https://i.ibb.co/qdH3hqN/image.webp",
    quantity: 1,
    price: 500,
    productType: "cream",
  },
  {
    id: "el241",
    name: "Moisturizing Крем для рук увлажняющий 125 мл",
    img: "https://i.ibb.co/d6PNCrG/image.webp",
    quantity: 1,
    price: 225,
    productType: "cream",
  },
  {
    id: "el242",
    name: "Moisturizing Крем для рук увлажняющий 400 мл",
    img: "https://i.ibb.co/d6PNCrG/image.webp",
    quantity: 1,
    price: 500,
    productType: "cream",
  },
  {
    id: "el243",
    name: "Protective Regenerating Крем для рук защитно-регенерирующий 125 мл",
    img: "https://i.ibb.co/8dMyq2m/image.webp",
    quantity: 1,
    price: 270,
    productType: "cream",
  },
  {
    id: "el244",
    name: "Protective Regenerating Крем для рук защитно-регенерирующий 400 мл",
    img: "https://i.ibb.co/8dMyq2m/image.webp",
    quantity: 1,
    price: 600,
    productType: "cream",
  },
  //Styling
  {
    id: "el245",
    name: "Perfect Shine Спрей-блеск 250 мл",
    img: "https://i.ibb.co/pfwKn87/Crodabond-CSA-PERFECT-SHINE-250.png",
    quantity: 1,
    price: 750,
    productType: "styling",
  },
  {
    id: "el246",
    name: "Extrastrong Лак для волос экстрасильной фиксации 500 мл",
    img: "https://i.ibb.co/NtK1TXF/EXTRASTRONG-500.png",
    quantity: 1,
    price: 560,
    productType: "styling",
  },
  {
    id: "el247",
    name: "Ultrastrong Лак для волос ультрасильной фиксации 500 мл",
    img: "https://i.ibb.co/qN5jxtc/ULTRASTRONG-500.png",
    quantity: 1,
    price: 560,
    productType: "styling",
  },
  {
    id: "el248",
    name: "Спрей разглаживающий для волос с термозащитным комплексом Silk Surface 250 мл",
    img: "https://i.ibb.co/7rFvqJ7/SILK-SURFACE-250.jpg",
    quantity: 1,
    price: 570,
    productType: "styling",
  },
  {
    id: "el249",
    name: "Спрей для прикорневого объема с антистатическим комплексом Volume Booster 250 мл",
    img: "https://i.ibb.co/syjQhv6/VOLUME-BOOSTER-250.jpg",
    quantity: 1,
    price: 570,
    productType: "styling",
  },
  {
    id: "el250",
    name: "Спрей для волос сильной фиксацstoии с термозащитный комплексом Five Elements 250 мл",
    img: "https://i.ibb.co/Rhs52mT/FIVE-ELEMENTS-250.jpg",
    quantity: 1,
    price: 570,
    productType: "styling",
  },
  {
    id: "el251",
    name: "Спрей Heat Shield для волос с термозащитой 300 мл",
    img: "https://i.ibb.co/jLfPGXx/HEAT-SHIELD.png",
    quantity: 1,
    price: 480,
    productType: "care",
  },
];

let catalogKapous = [
  {
    id: "el252",
    name: "Флюид для секущихся кончиков волос с гиалуроновой кислотой серии `Hyaluronic Acid`, 80 мл",
    img: "https://i.ibb.co/D1Pg0qd/80.jpg",
    quantity: 1,
    price: 380,
    productType: "care",
  },
  {
    id: "el253",
    name: "Двухфазная сыворотка для волос с антижелтым эффектом серии `Blond Bar`, 200 мл",
    img: "https://i.ibb.co/9y10Ssx/200.jpg",
    quantity: 1,
    price: 400,
    productType: "care",
  },
  {
    id: "el254",
    name: "Питательный оттеночный шампунь для оттенков блонд серии `Blond Bar`, Серебро, 200 мл",
    img: "https://i.ibb.co/N2Xp0KN/200.jpg",
    quantity: 1,
    price: 350,
    productType: "shampoo",
  },
  {
    id: "el255",
    name: "Питательный оттеночный шампунь для оттенков блонд серии `Blond Bar`, Стальной, 200 мл",
    img: "https://i.ibb.co/sbrpkzr/200.jpg",
    quantity: 1,
    price: 350,
    productType: "shampoo",
  },
  {
    id: "el256",
    name: "Питательный оттеночный шампунь для оттенков блонд серии `Blond Bar`, Розовый, 200 мл",
    img: "https://i.ibb.co/QQCwh9d/200.jpg",
    quantity: 1,
    price: 350,
    productType: "shampoo",
  },
  {
    id: "el257",
    name: "Питательный оттеночный шампунь для оттенков блонд серии `Blond Bar`, Пепельный, 200 мл",
    img: "https://i.ibb.co/vxgxYLB/200.jpg",
    quantity: 1,
    price: 350,
    productType: "shampoo",
  },
  {
    id: "el258",
    name: "Питательный оттеночный шампунь для оттенков блонд серии `Blond Bar`, Платиновый, 200 мл",
    img: "https://i.ibb.co/vQzwTHB/200.jpg",
    quantity: 1,
    price: 350,
    productType: "shampoo",
  },
  {
    id: "el259",
    name: "Питательный оттеночный шампунь для оттенков блонд серии `Blond Bar`, Бежевый, 200 мл",
    img: "https://i.ibb.co/wNYhwKm/200.jpg",
    quantity: 1,
    price: 350,
    productType: "shampoo",
  },
  {
    id: "el260",
    name: "Питательный оттеночный бальзам для оттенков блонд серии `Blond Bar`, Стальной, 200 мл",
    img: "https://i.ibb.co/37ngW1v/200.jpg",
    quantity: 1,
    price: 380,
    productType: "balsam",
  },
  {
    id: "el261",
    name: "Питательный оттеночный бальзам для оттенков блонд серии `Blond Bar`, Серебро, 200 мл",
    img: "https://i.ibb.co/rxg6Dp5/200.jpg",
    quantity: 1,
    price: 380,
    productType: "balsam",
  },
  {
    id: "el262",
    name: "Питательный оттеночный бальзам для оттенков блонд серии `Blond Bar`, Розовый, 200 мл",
    img: "https://i.ibb.co/f4qvL8C/200.jpg",
    quantity: 1,
    price: 380,
    productType: "balsam",
  },
  {
    id: "el263",
    name: "Питательный оттеночный бальзам для оттенков блонд серии `Blond Bar`, Платиновый, 200 мл",
    img: "https://i.ibb.co/71ZCn52/200.jpg",
    quantity: 1,
    price: 380,
    productType: "balsam",
  },
  {
    id: "el264",
    name: "Питательный оттеночный бальзам для оттенков блонд серии `Blond Bar`, Бежевый, 200 мл",
    img: "https://i.ibb.co/dQQ2ccV/200.jpg",
    quantity: 1,
    price: 380,
    productType: "balsam",
  },
  {
    id: "el265",
    name: "Питательный оттеночный бальзам для оттенков блонд серии `Blond Bar`, Пепельный, 200 мл",
    img: "https://i.ibb.co/tMcwrT4/200.jpg",
    quantity: 1,
    price: 380,
    productType: "balsam",
  },
  {
    id: "el266",
    name: "Питательный оттеночный бальзам для оттенков блонд серии `Blond Bar`, Перламутровый, 200 мл",
    img: "https://i.ibb.co/TqjLbXb/200.jpg",
    quantity: 1,
    price: 380,
    productType: "balsam",
  },
  {
    id: "el267",
    name: "Увлажняющая сыворотка для восстановления волос «Dual Renascence 2 phase», 200 мл",
    img: "https://i.ibb.co/pKZFQhS/Dual-Renascence-2-phase-200.jpg",
    quantity: 1,
    price: 350,
    productType: "care",
  },
  {
    id: "el268",
    name: "Увлажняющая сыворотка для восстановления волос «Dual Renascence 2 phase», 500 мл",
    img: "https://i.ibb.co/H2Q9MPH/Dual-Renascence-2-phase-500.jpg",
    quantity: 1,
    price: 590,
    productType: "care",
  },
  {
    id: "el269",
    name: "Сыворотка-уход для окрашенных волос «Dual Renascence 2 phase», 200 мл",
    img: "https://i.ibb.co/JnHBLNM/Dual-Renascence-2-phase-200.jpg",
    quantity: 1,
    price: 350,
    productType: "care",
  },
  {
    id: "el270",
    name: "Сыворотка-уход для окрашенных волос «Dual Renascence 2 phase», 500 мл",
    img: "https://i.ibb.co/BtfK0mj/Dual-Renascence-2-phase-500.jpg",
    quantity: 1,
    price: 590,
    productType: "care",
  },
  {
    id: "el271",
    name: "Флюид для секущихся кончиков волос «Crystal Shine», 60 мл",
    img: "https://i.ibb.co/BtfK0mj/Dual-Renascence-2-phase-500.jpg",
    quantity: 1,
    price: 380,
    productType: "care",
  },
  {
    id: "el272",
    name: "Шампунь для всех типов волос с ароматом ментола, 1000 мл",
    img: "https://i.ibb.co/LQr4X74/1000.jpg",
    quantity: 1,
    price: 310,
    productType: "shampoo",
  },
  {
    id: "el273",
    name: "Сухой шампунь для волос «Fresh&Up», 150 мл",
    img: "https://i.ibb.co/PwWQzSc/Fresh-Up-150.jpg",
    quantity: 1,
    price: 290,
    productType: "shampoo",
  },
  {
    id: "el274",
    name: "Сухой шампунь для волос «Fresh&Up», 400 мл",
    img: "https://i.ibb.co/m6zHkm8/Fresh-Up-400.jpg",
    quantity: 1,
    price: 550,
    productType: "shampoo",
  },
  {
    id: "el275",
    name: "Бальзам для окрашенных волос, 1000 мл",
    img: "https://i.ibb.co/QHkmT3w/1000.jpg",
    quantity: 1,
    price: 400,
    productType: "balsam",
  },
  {
    id: "el276",
    name: "Шампунь для окрашенных волос, 1000 мл",
    img: "https://i.ibb.co/mH2n07P/1000.jpg",
    quantity: 1,
    price: 420,
    productType: "shampoo",
  },
  {
    id: "el277",
    name: "Лак аэрозольный для волос нормальной фиксации «Lacca Normal», 100 мл",
    img: "https://i.ibb.co/q1jMMsd/Lacca-Normal-100.jpg",
    quantity: 1,
    price: 210,
    productType: "styling",
  },
  {
    id: "el278",
    name: "Лак аэрозольный для волос нормальной фиксации «Lacca Normal», 500 мл",
    img: "https://i.ibb.co/4JFsh2p/Lacca-Normal-500.jpg",
    quantity: 1,
    price: 400,
    productType: "styling",
  },
  {
    id: "el279",
    name: "Спрей для придания объема на корнях «Root Volume», 250 мл",
    img: "https://i.ibb.co/9TKXyBM/Root-Volume-250.jpg",
    quantity: 1,
    price: 330,
    productType: "styling",
  },
  {
    id: "el280",
    name: "Моделирующая паста для волос сильной фиксации «Matt Gloss», 100 мл",
    img: "https://i.ibb.co/fMZfXS5/Matt-Gloss-100.jpg",
    quantity: 1,
    price: 360,
    productType: "styling",
  },
  {
    id: "el281",
    name: "Крем-воск для волос нормальной фиксации «Luster», 100 мл",
    img: "https://i.ibb.co/865TybT/Luster-100.jpg",
    quantity: 1,
    price: 360,
    productType: "styling",
  },
  {
    id: "el282",
    name: "Водный воск нормальной фиксации «Elaborate», 100 мл",
    img: "https://i.ibb.co/M75TrHt/Elaborate-100.jpg",
    quantity: 1,
    price: 340,
    productType: "styling",
  },
  {
    id: "el283",
    name: "Текстурирующий пудинг для укладки волос экстра сильной фиксации «Pudding Creator», 100 мл",
    img: "https://i.ibb.co/TknvwKv/Pudding-Creator-100.png",
    quantity: 1,
    price: 350,
    productType: "styling",
  },
  {
    id: "el284",
    name: "Глина для укладки волос нормальной фиксации «Sculpture Clay», 100 мл",
    img: "https://i.ibb.co/xCxL9bV/Sculpture-Clay-100.png",
    quantity: 1,
    price: 340,
    productType: "styling",
  },
  {
    id: "el285",
    name: "Гель для волос нормальной фиксации «Gel Normal», 150 мл",
    img: "https://i.ibb.co/WkzGFr8/Gel-Normal-150.png",
    quantity: 1,
    price: 280,
    productType: "styling",
  },
  {
    id: "el286",
    name: "Гель для волос сильной фиксации «Gel Strong», 150 мл",
    img: "https://i.ibb.co/56T87Jf/Gel-Strong-150.jpg",
    quantity: 1,
    price: 290,
    productType: "styling",
  },
  {
    id: "el287",
    name: "Кремовый шёлк для волос, 150 мл",
    img: "https://i.ibb.co/3SXkMD4/150.jpg",
    quantity: 1,
    price: 360,
    productType: "care",
  },
  {
    id: "el288",
    name: "Лосьон для термозащиты волос «Thermo barrier», 200 мл",
    img: "https://i.ibb.co/R0N3Ht8/Thermo-barrier-200.jpg",
    quantity: 1,
    price: 380,
    productType: "care",
  },
  {
    id: "el289",
    name: "Блеск для волос «Starbright», 300 мл",
    img: "https://i.ibb.co/nzqPDrr/Starbright-300.jpg",
    quantity: 1,
    price: 300,
    productType: "care",
  },
  {
    id: "el290",
    name: "Пудра для создания объема на волосах «Volumetrick», 7 г",
    img: "https://i.ibb.co/7K8k8nZ/Volumetrick-7.jpg",
    quantity: 1,
    price: 330,
    productType: "styling",
  },
  {
    id: "el291",
    name: "Шампунь для кудрявых волос, 300 мл",
    img: "https://i.ibb.co/V2zZPGB/300.png",
    quantity: 1,
    price: 270,
    productType: "shampoo",
  },
  {
    id: "el292",
    name: "Бальзам для кудрявых волос, 300 мл",
    img: "https://i.ibb.co/QpdpH20/300.png",
    quantity: 1,
    price: 260,
    productType: "balsam",
  },
  {
    id: "el293",
    name: "Усилитель для прямых и кудрявых волос двойного действия «Amplifier», 300 мл",
    img: "https://i.ibb.co/NCrCFQ4/Amplifier-300.jpg",
    quantity: 1,
    price: 430,
    productType: "styling",
  },
  {
    id: "el294",
    name: "Шампунь для прямых волос, 300 мл",
    img: "https://i.ibb.co/C71551K/300.jpg",
    quantity: 1,
    price: 270,
    productType: "shampoo",
  },
  {
    id: "el295",
    name: "Бальзам для прямых волос, 200 мл",
    img: "https://i.ibb.co/J5jnz3j/200.jpg",
    quantity: 1,
    price: 260,
    productType: "balsam",
  },
  {
    id: "el296",
    name: "Двухфазное масло для волос с маслом ореха макадамии, 200 мл",
    img: "https://i.ibb.co/S7cRYNp/200.jpg",
    quantity: 1,
    price: 580,
    productType: "care",
  },
  {
    id: "el297",
    name: "Флюид с маслом ореха макадамии, 100 мл",
    img: "https://i.ibb.co/4ZTNyqP/100.jpg",
    quantity: 1,
    price: 570,
    productType: "care",
  },
  {
    id: "el298",
    name: "Двухфазная сыворотка для волос с маслом ореха макадамии, 200 мл",
    img: "https://i.ibb.co/SyHW3yx/200.jpg",
    quantity: 1,
    price: 380,
    productType: "care",
  },
  {
    id: "el299",
    name: "Бальзам с маслом ореха макадамии, 200 мл",
    img: "https://i.ibb.co/SNvBf6G/200.jpg",
    quantity: 1,
    price: 370,
    productType: "balsam",
  },
  {
    id: "el300",
    name: "Маска для волос с маслом ореха макадамии, 500 мл",
    img: "https://i.ibb.co/PxW5Hmp/500.jpg",
    quantity: 1,
    price: 440,
    productType: "mask",
  },
  {
    id: "el301",
    name: "Блеск-шампунь для волос «Brilliants gloss», 250 мл",
    img: "https://i.ibb.co/Ry4vKDp/Brilliants-gloss-250.jpg",
    quantity: 1,
    price: 340,
    productType: "shampoo",
  },
  {
    id: "el302",
    name: "Шампунь с маслом ореха макадамии, 250 мл",
    img: "https://i.ibb.co/59zTNMZ/250.jpg",
    quantity: 1,
    price: 450,
    productType: "shampoo",
  },
  {
    id: "el303",
    name: "Моющий кондиционер «Co-Wash» для окрашенных волос, 300 мл",
    img: "https://i.ibb.co/kJZVVgb/Co-Wash-300.jpg",
    quantity: 1,
    price: 270,
    productType: "shampoo",
  },
  {
    id: "el304",
    name: "Моющий кондиционер «Co-Wash» для сухих и поврежденных волос, 300 мл",
    img: "https://i.ibb.co/HBZ0gwj/Co-Wash-300.jpg",
    quantity: 1,
    price: 270,
    productType: "shampoo",
  },
  {
    id: "el305",
    name: "Мужской тонизирующий шампунь 3 в 1, 1000 мл",
    img: "https://i.ibb.co/34rKz4t/3-1-1000.jpg",
    quantity: 1,
    price: 610,
    productType: "shampoo",
  },
  {
    id: "el306",
    name: "Экспресс-маска для восстановления волос 2 фазы серии «Magic Keratin» 2*12 мл",
    img: "https://i.ibb.co/QYQbTpn/12-12.jpg",
    quantity: 1,
    price: 00,
    productType: "mask",
  },
  {
    id: "el307",
    name: "Флюид для секущихся кончиков волос с кератином, 80 мл",
    img: "https://i.ibb.co/7Nrtyw2/80.jpg",
    quantity: 1,
    price: 360,
    productType: "care",
  },
  {
    id: "el308",
    name: "Масло арганы для волос «Arganoil» 75 мл",
    img: "https://i.ibb.co/g49V4Qb/75.jpg",
    quantity: 1,
    price: 550,
    productType: "care",
  },
  {
    id: "el309",
    name: "Масло арганы для волос «Arganoil» 200 мл",
    img: "https://i.ibb.co/k27QFDt/200.jpg",
    quantity: 1,
    price: 770,
    productType: "care",
  },
  {
    id: "el310",
    name: "Укрепляющая сыворотка с биотином для стимуляции роста волос «Biotin Energy», 200 мл",
    img: "https://i.ibb.co/NKSPDvX/200.jpg",
    quantity: 1,
    price: 350,
    productType: "care",
  },
  {
    id: "el311",
    name: "Флюид для секущихся кончиков волос с биотином «Biotin Energy», 80 мл",
    img: "https://i.ibb.co/dMjFpnD/80.jpg",
    quantity: 1,
    price: 360,
    productType: "care",
  },
  {
    id: "el312",
    name: "Шампунь против перхоти Treatment, 250 мл",
    img: "https://i.ibb.co/ryMrrRv/Treatment-250.jpg",
    quantity: 1,
    price: 290,
    productType: "shampoo",
  },
  {
    id: "el313",
    name: "Лосьон против перхоти Treatment, 100 мл",
    img: "https://i.ibb.co/8X9Z4dX/Treatment-100.jpg",
    quantity: 1,
    price: 320,
    productType: "care",
  },
  {
    id: "el314",
    name: "Лосьон против перхоти в ампулах Treatment, 5*10 мл",
    img: "https://i.ibb.co/SrQ7Wg2/Treatment-5-10.jpg",
    quantity: 1,
    price: 510,
    productType: "care",
  },
  {
    id: "el315",
    name: "Шампунь против выпадения волос Treatment, 250 мл",
    img: "https://i.ibb.co/VN9xRx1/Treatment-250.jpg",
    quantity: 1,
    price: 290,
    productType: "shampoo",
  },
  {
    id: "el316",
    name: "Лосьон против выпадения волос Treatment, 100 мл",
    img: "https://i.ibb.co/gmPFnDf/Treatment-100.jpg",
    quantity: 1,
    price: 320,
    productType: "care",
  },
  {
    id: "el317",
    name: "Лосьон против выпадения волос в ампулах Treatment, 5*10 мл",
    img: "https://i.ibb.co/p6qPq03/Treatment-5-10.jpg",
    quantity: 1,
    price: 510,
    productType: "care",
  },
  {
    id: "el318",
    name: "Очищающий скраб для кожи головы «PreTreatment», 150 мл",
    img: "https://i.ibb.co/R2vBPHj/150.jpg",
    quantity: 1,
    price: 340,
    productType: "care",
  },
  {
    id: "el319",
    name: "Флюид для поврежденных кончиков  волос «Treatment», 60 мл",
    img: "https://i.ibb.co/bsGPpDQ/60.jpg",
    quantity: 1,
    price: 340,
    productType: "care",
  },
  {
    id: "el320",
    name: "Сухой шампунь для волос, 150 мл",
    img: "https://i.ibb.co/TH3ZDm5/150.jpg",
    quantity: 1,
    price: 290,
    productType: "shampoo",
  },
  {
    id: "el321",
    name: "Кристальные капли для секущихsся кончиков волос «Crystal drops», 80 мл",
    img: "https://i.ibb.co/qBDjfp8/Crystal-drops-80.jpg",
    quantity: 1,
    price: 350,
    productType: "care",
  },
  {
    id: "el322",
    name: "Шампунь для волос Анти-желтый «Antiyellow» линии Studio Professional, 200 мл",
    img: "https://i.ibb.co/0DxkHpX/Antiyellow-250.jpg",
    quantity: 1,
    price: 190,
    productType: "shampoo",
  },
  {
    id: "el323",
    name: "Увлажняющая сыворотка с пшеничными протеинами «Finish Bi-Phase», 200 мл",
    img: "https://i.ibb.co/G9VXYNd/Finish-Bi-Phase-200.jpg",
    quantity: 1,
    price: 310,
    productType: "care",
  },
  {
    id: "el324",
    name: "Увлажняющая сыворотка с пшеничными протеинами «Finish Bi-Phase», 500 мл",
    img: "https://i.ibb.co/ySddPdd/Finish-Bi-Phase-500.jpg",
    quantity: 1,
    price: 470,
    productType: "care",
  },
  {
    id: "el325",
    name: "Крем-Крем-спрей для волос 15 в 1 серии «Styling» линии Studio Professional, 200 мл",
    img: "https://i.ibb.co/tYqbrfT/15-1-200.jpg",
    quantity: 1,
    price: 240,
    productType: "care",
  },
  {
    id: "el326",
    name: "Блеск-флюид для волос «Diamond Dews», 300 мл",
    img: "https://i.ibb.co/gWJNPr2/Diamond-Dews-300.jpg",
    quantity: 1,
    price: 300,
    productType: "care",
  },
  {
    id: "el327",
    name: "Матовый воск для укладки волос сильной фиксации «Matt Wax» серии «Styling» линии Studio Professional, 125 мл",
    img: "https://i.ibb.co/s9yQ47w/Matt-Wax-125.jpg",
    quantity: 1,
    price: 330,
    productType: "styling",
  },
  {
    id: "el328",
    name: "Водный воск нормальной фиксации серии «Styling» линии Studio Professional, 125 мл",
    img: "https://i.ibb.co/VHxz47z/125.png",
    quantity: 1,
    price: 300,
    productType: "styling",
  },
  {
    id: "el329",
    name: "Гель для волос сильной фиксации серии «Styling» линии Studio Professional, 150 мл",
    img: "https://i.ibb.co/sHvTzNp/150.png",
    quantity: 1,
    price: 270,
    productType: "styling",
  },
  {
    id: "el330",
    name: "Восстанавливающий шампунь с амино-бустер комплексом серии «Total Reconstruction» линии Studio Professional, 400 мл",
    img: "https://i.ibb.co/1f4VxG2/400.jpg",
    quantity: 1,
    price: 400,
    productType: "shampoo",
  },
  {
    id: "el331",
    name: "Восстанавливающая маска серии «Total Reconstruction» линии Studio Professional, 400 мл",
    img: "https://i.ibb.co/HYq4ZQy/400.jpg",
    quantity: 1,
    price: 310,
    productType: "mask",
  },
  {
    id: "el332",
    name: "Восстанавливающий бустер с амино-бустер комплексом серии «Total Reconstruction» линии Studio Professional, 150 мл",
    img: "https://i.ibb.co/PY94pDj/150.jpg",
    quantity: 1,
    price: 200,
    productType: "care",
  },
  {
    id: "el333",
    name: "Восстанавливающий спрей серии «Total Reconstruction» линии Studio Professional, 150 мл",
    img: "https://i.ibb.co/V2RSVvj/150.jpg",
    quantity: 1,
    price: 250,
    productType: "care",
  },
  {
    id: "el334",
    name: "Двухфазная сыворотка для волос с маслами Авокадо и Оливы линии Studio Professional, 200 мл",
    img: "https://i.ibb.co/FbFvC9G/200.jpg",
    quantity: 1,
    price: 310,
    productType: "care",
  },
  {
    id: "el335",
    name: "Двухфазная сыворотка для волос с маслами Авокадо и Оливы линии Studio Professional, 500 мл",
    img: "https://i.ibb.co/Cs8QGKh/500.jpg",
    quantity: 1,
    price: 460,
    productType: "care",
  },
  {
    id: "el336",
    name: "Флюид для секущихся кончиков волос с маслами Авокадо и Оливы линии Studio Professional, 80 мл",
    img: "https://i.ibb.co/6D8zDCn/80.png",
    quantity: 1,
    price: 320,
    productType: "care",
  },
  {
    id: "el337",
    name: "Питательная маска для волос с маслами Авокадо и Оливы линии Studio Professional, 500 мл",
    img: "https://i.ibb.co/YLgdrcW/500.png",
    quantity: 1,
    price: 290,
    productType: "mask",
  },
  {
    id: "el338",
    name: "Шампунь для волос с маслами Авокадо и Оливы линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/rGjHCrf/350.jpg",
    quantity: 1,
    price: 160,
    productType: "shampoo",
  },
  {
    id: "el339",
    name: "Шампунь для волос с маслами Авокадо и Оливы линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/CmRmQPh/1000.png",
    quantity: 1,
    price: 320,
    productType: "shampoo",
  },
  {
    id: "el340",
    name: "Увлажняющий бальзам для волос с маслами Авокадо и Оливы линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/BBBxMpv/350.jpg",
    quantity: 1,
    price: 150,
    productType: "balsam",
  },
  {
    id: "el341",
    name: "Увлажняющий бальзам для волос с маслами Авокадо и Оливы линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/8bzXZz5/1000.png",
    quantity: 1,
    price: 340,
    productType: "balsam",
  },
  {
    id: "el342",
    name: "Шампунь для всех типов волос «Малина» серии «Aromatic Symphony» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/D96tSGB/350.jpg",
    quantity: 1,
    price: 140,
    productType: "shampoo",
  },
  {
    id: "el343",
    name: "Шампунь для всех типов волос «Малина» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/6bdcts5/1000.jpg",
    quantity: 1,
    price: 310,
    productType: "shampoo",
  },
  {
    id: "el344",
    name: "Бальзам для всех типов волос «Малина» серии «Aromatic Symphony» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/YQm62kj/350.jpg",
    quantity: 1,
    price: 140,
    productType: "balsam",
  },
  {
    id: "el345",
    name: "Бальзам для всех типов волос «Малина» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/0JJh7nW/1000.jpg",
    quantity: 1,
    price: 320,
    productType: "balsam",
  },
  {
    id: "el346",
    name: "Шампунь для всех типов волос «Банан и дыня» серии «Aromatic Symphony» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/SB96CW5/350.jpg",
    quantity: 1,
    price: 140,
    productType: "shampoo",
  },
  {
    id: "el347",
    name: "Шампунь для всех типов волос «Банан и дыня» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/R0rMf6Y/1000.jpg",
    quantity: 1,
    price: 310,
    productType: "shampoo",
  },
  {
    id: "el348",
    name: "Бальзам для всех типов волос «Банан и дыня» серии «Aromatic Symphony» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/LpgLwh1/350.jpg",
    quantity: 1,
    price: 140,
    productType: "balasm",
  },
  {
    id: "el349",
    name: "Бальзам для всех типов волос «Банан и дыня» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/bbYN6wT/1000.jpg",
    quantity: 1,
    price: 310,
    productType: "balasm",
  },
  {
    id: "el350",
    name: "Шампунь для всех типов волос «Молочко миндального ореха» серии «Aromatic Symphony» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/8r4yXVp/350.jpgs",
    quantity: 1,
    price: 140,
    productType: "shampoo",
  },
  {
    id: "el351",
    name: "Шампунь для всех типов волос «Молочко миндального ореха» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/zJBY1hg/1000.jpg",
    quantity: 1,
    price: 310,
    productType: "shampoo",
  },
  {
    id: "el352",
    name: "Бальзам для всех типов волос «Молочко миндального ореха» серии «Aromatic Symphony» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/TKzW1Xd/350.jpg",
    quantity: 1,
    price: 140,
    productType: "balsam",
  },
  {
    id: "el353",
    name: "Бальзам для всех типов волос «Молочко миндального ореха» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/zPQSMCn/1000.jpg",
    quantity: 1,
    price: 310,
    productType: "balsam",
  },
  {
    id: "el354",
    name: "Шампунь для всех типов волос «Молоко и мед» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/zPQSMCn/1000.jpg",
    quantity: 1,
    price: 310,
    productType: "shampoo",
  },
  {
    id: "el355",
    name: "Бальзам для всех типов волос «Молоко и мед» серии «Aromatic Symphony» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/BfLv8bZ/350.jpg",
    quantity: 1,
    price: 140,
    productType: "balsam",
  },
  {
    id: "el356",
    name: "Бальзам для всех типов волос «Молоко и мед» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/2c3HfTK/1000.jpg",
    quantity: 1,
    price: 320,
    productType: "balsam",
  },
  {
    id: "el357",
    name: "Шампунь для всех типов волос «Маракуйя» серии «Aromatic Symphony» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/ZLnWJWm/350.jpg",
    quantity: 1,
    price: 140,
    productType: "shampoo",
  },
  {
    id: "el358",
    name: "Шампунь для всех типов волос «Маракуйя» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/1z0ZLNY/1000.jpg",
    quantity: 1,
    price: 310,
    productType: "shampoo",
  },
  {
    id: "el359",
    name: "Бальзам для всех типов волос «Маракуйя» серии «Aromatic Symphony» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/tzx6gQY/350.jpg",
    quantity: 1,
    price: 140,
    productType: "balsam",
  },
  {
    id: "el360",
    name: "Бальзам для всех типов волос «Маракуйя» серии «Aromatic Symphony» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/tzx6gQY/350.jpg",
    quantity: 1,
    price: 310,
    productType: "balsam",
  },
  {
    id: "el361",
    name: "Шелк-Шампунь с протеинами шелка серии «Luxe Care» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/Pxk083k/Luxe-Care-350.jpg",
    quantity: 1,
    price: 200,
    productType: "shampoo",
  },
  {
    id: "el362",
    name: "Шелк-Шампунь с протеинами шелка серии «Luxe Care» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/my3dSFp/Luxe-Care-1000.png",
    quantity: 1,
    price: 420,
    productType: "shampoo",
  },
  {
    id: "el363",
    name: "Шелк-Шампунь с протеинами шелка серии «Luxe Care» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/zRQ65Bk/Luxe-Care-350.jpg",
    quantity: 1,
    price: 200,
    productType: "balsam",
  },
  {
    id: "el364",
    name: 'Шелк-Шампунь с протеинами шелка серии «Luxe Care» линии Studio Professional, 1000 мл"',
    img: "https://i.ibb.co/MsMKrHn/Luxe-Care-1000.png",
    quantity: 1,
    price: 420,
    productType: "balsam",
  },
  {
    id: "el365",
    name: "Кашемир-Бальзам с протеинами шелка серии «Luxe Care» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/FzX9DSd/Luxe-Care-350.jpg",
    quantity: 1,
    price: 200,
    productType: "balsam",
  },
  {
    id: "el366",
    name: "Бархат-Шампунь с протеинами шелка серии «Luxe Care» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/RBsVJg2/Luxe-Care-350.jpg",
    quantity: 1,
    price: 200,
    productType: "shampoo",
  },
  {
    id: "el367",
    name: "Бархат-Шампунь с протеинами кашемира и маслом льна серии «Luxe Care» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/cy9pSv4/Luxe-Care-1000.png",
    quantity: 1,
    price: 420,
    productType: "shampoo",
  },
  {
    id: "el368",
    name: "Бархат-Бальзам с протеинами кашемира и маслом льна серии «Luxe Care» линии Studio Professional, 350 мл",
    img: "https://i.ibb.co/xLhFTZg/Luxe-Care-350.jpg",
    quantity: 1,
    price: 200,
    productType: "balsam",
  },
  {
    id: "el369",
    name: "Бархат-Бальзам с протеинами кашемира и маслом льна серии «Luxe Care» линии Studio Professional, 1000 мл",
    img: "https://i.ibb.co/zXQR5mr/Luxe-Care-1000.png",
    quantity: 1,
    price: 420,
    productType: "balsam",
  },

  {
    id: "el370",
    name: "Мужской карбоновый шампунь серии «Gentlemen» Kapous, 250 мл",
    img: "https://i.ibb.co/m4ynjzj/250.jpg",
    quantity: 1,
    price: 210,
    productType: "men",
  },
  {
    id: "el371",
    name: "Мужской карбоновый шампунь серии «Gentlemen» Kapous, 1000 мл",
    img: "https://i.ibb.co/mHNytvc/1000.jpg",
    quantity: 1,
    price: 560,
    productType: "men",
  },
  {
    id: "el372",
    name: "Мужской тонизирующий шампунь 3 в 1 серии «Gentlemen», 250 мл",
    img: "https://i.ibb.co/whdbFPN/3-1-250.jpg",
    quantity: 1,
    price: 280,
    productType: "men",
  },
  {
    id: "el373",
    name: "Увлажняющий мужской гель для душа с экстрактом оливы серии «Gentlemen», 250 мл",
    img: "https://i.ibb.co/7z9V38M/250.jpg",
    quantity: 1,
    price: 330,
    productType: "men",
  },
];

let catalogConstant_Delight = [
  {
    id: "el374",
    name: "Эликсир многофункциональный 12 в 1, 200 мл",
    img: "https://i.ibb.co/Kb75NSN/CONSTANT-DELIGHT-12-1-200.webp",
    quantity: 1,
    price: 700,
    productType: "care",
  },
  {
    id: "el375",
    name: "Маска MAGIC 5 OILS для восстановления волос, 500 мл",
    img: "https://i.ibb.co/JvVfzHM/CONSTANT-DELIGHT-MAGIC-5-OILS-500.webp",
    quantity: 1,
    price: 700,
    productType: "mask",
  },
  {
    id: "el376",
    name: "Средство для восстановления волос «Капельки шелка» с протеинами шелка, 80 мл",
    img: "https://i.ibb.co/Fz9Pf1j/CONSTANT-DELIGHT-80.webp",
    quantity: 1,
    price: 650,
    productType: "care",
  },
  {
    id: "el377",
    name: "Жидкие кристаллы MAGIC 5 OILS без фиксации, 80 мл",
    img: "https://i.ibb.co/xXHxYYv/CONSTANT-DELIGHT-MAGIC-5-OILS-80.webp",
    quantity: 1,
    price: 550,
    productType: "care",
  },
  {
    id: "el378",
    name: "Маска для восстановления волос СПА-уход с протеинами шелка, 500 мл",
    img: "https://i.ibb.co/fYxNB28/CONSTANT-DELIGHT-500.webp",
    quantity: 1,
    price: 700,
    productType: "mask",
  },
  {
    id: "el379",
    name: "Лосьон BARBER CARE против выпадения волос 100 мл",
    img: "https://i.ibb.co/YNkS7fS/CONSTANT-DELIGHT-BARBER-CARE-100.webp",
    quantity: 1,
    price: 800,
    productType: "care",
  },
  {
    id: "el380",
    name: "Лосьон-концентрат против выпадения волос 100 мл",
    img: "https://i.ibb.co/DbTn6hH/CONSTANT-DELIGHT-100.webp",
    quantity: 1,
    price: 1100,
    productType: "care",
  },
  {
    id: "el381",
    name: "Кондиционер MAGIC 5 OILS для восстановления волос 250 мл",
    img: "https://i.ibb.co/rmWnXVZ/CONSTANT-DELIGHT-MAGIC-5-OILS-250.webp",
    quantity: 1,
    price: 550,
    productType: "care",
  },
  {
    id: "el382",
    name: "Кондиционер MAGIC 5 OILS для восстановления волос 1000 мл",
    img: "https://i.ibb.co/Pc82CWm/CONSTANT-DELIGHT-MAGIC-5-OILS-1000.webp",
    price: 1050,
    productType: "balsam",
  },
  {
    id: "el383",
    name: "Спрей MAGIC 5 OILS без фиксации термозащитный 200 мл",
    img: "https://i.ibb.co/CngsYLr/CONSTANT-DELIGHT-MAGIC-5-OILS-200.webp",
    quantity: 1,
    price: 750,
    productType: "care",
  },
  {
    id: "el384",
    name: "Маска для роста волос 250 мл",
    img: "https://i.ibb.co/RYjB1yX/CONSTANT-DELIGHT-250.webp",
    quantity: 1,
    price: 550,
    productType: "mask",
  },
  {
    id: "el385",
    name: "Шампунь против выпадения волос 250 мл",
    img: "https://i.ibb.co/k1bBdJX/CONSTANT-DELIGHT-250.webp",
    quantity: 1,
    price: 500,
    productType: "shampoo",
  },
  {
    id: "el386",
    name: "Шампунь MAGIC 5 OILS для очищения волос интенсивный 250 мл",
    img: "https://i.ibb.co/VCd67Vp/CONSTANT-DELIGHT-MAGIC-5-OILS-250.webp",
    quantity: 1,
    price: 650,
    productType: "shampoo",
  },
  {
    id: "el387",
    name: "Кондиционер BARBER CARE для ежедневного ухода 250 мл",
    img: "https://i.ibb.co/BcLqqMt/CONSTANT-DELIGHT-BARBER-CARE-250.webp",
    quantity: 1,
    price: 700,
    productType: "balsam",
  },
  {
    id: "el388",
    name: "Кондиционер BARBER CARE для ежедневного ухода 1000 мл",
    img: "https://i.ibb.co/9Njryk1/CONSTANT-DELIGHT-BARBER-CARE-1000.webp",
    quantity: 1,
    price: 1500,
    productType: "men",
  },
  {
    id: "el389",
    name: "Сухой шампунь MAGIC 5 OILS без фиксации 100 мл",
    img: "https://i.ibb.co/mXT9CT4/CONSTANT-DELIGHT-MAGIC-5-OILS-100.webp",
    quantity: 1,
    price: 550,
    productType: "shampoo",
  },
  {
    id: "el390",
    name: "Одеколон BARBER CARE после бритья многофункциональный Ice 400 мл",
    img: "https://i.ibb.co/zJ35jM9/CONSTANT-DELIGHT-BARBER-CARE-Ice-400.webp",
    quantity: 1,
    price: 2000,
    productType: "men",
  },
  {
    id: "el391",
    name: "Шампунь BARBER CARE против перхоти 1000 мл",
    img: "https://i.ibb.co/N1MJSs7/CONSTANT-DELIGHT-BARBER-CARE-1000.webp",
    quantity: 1,
    price: 2000,
    productType: "men",
  },
  {
    id: "el392",
    name: "Бальзам BARBER CARE после бритья 250 мл",
    img: "https://i.ibb.co/rtjTyYD/CONSTANT-DELIGHT-BARBER-CARE-250.webp",
    quantity: 1,
    price: 1400,
    productType: "men",
  },
  {
    id: "el393",
    name: "Гель BARBER CARE для бритья для точных контуров 150 мл",
    img: "https://i.ibb.co/YpzY0yS/CONSTANT-DELIGHT-BARBER-CARE-150.webp",
    quantity: 1,
    price: 750,
    productType: "men",
  },
  {
    id: "el394",
    name: "Масло BARBER CARE для бороды и усов 100 мл",
    img: "https://i.ibb.co/k9YzyKr/CONSTANT-DELIGHT-BARBER-CARE-100.webp",
    quantity: 1,
    price: 800,
    productType: "men",
  },
  {
    id: "el395",
    name: "Лосьон BARBER CARE после бритья 250 мл",
    img: "https://i.ibb.co/njJLs81/CONSTANT-DELIGHT-BARBER-CARE-250.webp",
    quantity: 1,
    price: 1600,
    productType: "men",
  },
  {
    id: "el396",
    name: "Крем BARBER CARE для бритья 250 мл",
    img: "https://i.ibb.co/8MH7133/CONSTANT-DELIGHT-BARBER-CARE-250.webp",
    quantity: 1,
    price: 950,
    productType: "men",
  },
  {
    id: "el397",
    name: "Шампунь BARBER CARE для ухода за бородой 200 мл",
    img: "https://i.ibb.co/HqxcZFn/CONSTANT-DELIGHT-BARBER-CARE-200.webp",
    quantity: 1,
    price: 700,
    productType: "men",
  },
  {
    id: "el398",
    name: "Мыло BARBER CARE для бритья 100 мл",
    img: "https://i.ibb.co/HBkzFbY/CONSTANT-DELIGHT-BARBER-CARE-100.webp",
    quantity: 1,
    price: 700,
    productType: "men",
  },
];

const Estel = catalogEstel;
const Epica = catalogEpica;
const Kapous = catalogKapous;
const Constant_Delight = catalogConstant_Delight;

const CATALOG = catalogEstel
  .concat(catalogEpica)
  .concat(catalogKapous)
  .concat(catalogConstant_Delight);
